"""Official ICAI study-material index.

The app stores only titles and official links. It does not mirror ICAI PDFs; every
card sends the learner to the source published by ICAI, respecting the notice on
the source page.
"""

ICAI_CATALOG: tuple[dict[str, str], ...] = (
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 1 · Theoretical Framework and Accounting Process", "title": "Foundation Paper 1 · Accounting · Module 1", "source": "https://resource.cdn.icai.org/93934bos-aps6170-ip-m1.pdf"},
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 2 · Partnership and Company Accounts", "title": "Foundation Paper 1 · Accounting · Module 2", "source": "https://resource.cdn.icai.org/94024bos-aps6170-ip-m2.pdf"},
    {"level": "CA Foundation", "subject": "Business Laws", "chapter": "Complete paper and latest applicable material", "title": "Foundation Paper 2 · Business Laws", "source": "https://www.icai.org/post/sm-foundation-paper2"},
    {"level": "CA Foundation", "subject": "Quantitative Aptitude", "chapter": "Complete paper and latest applicable material", "title": "Foundation Paper 3 · Quantitative Aptitude", "source": "https://www.icai.org/post/sm-foundation-paper3"},
    {"level": "CA Foundation", "subject": "Business Economics", "chapter": "Complete paper and latest applicable material", "title": "Foundation Paper 4 · Business Economics", "source": "https://www.icai.org/post/sm-foundation-paper4"},
    {"level": "CA Foundation", "subject": "Model Test Papers", "chapter": "Foundation model test papers", "title": "Foundation · Model Test Papers", "source": "https://resource.cdn.icai.org/84774bos68243.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 1 · Accounting Standards", "title": "Intermediate Paper 1 · Advanced Accounting · Module 1", "source": "https://resource.cdn.icai.org/93349bos-aps5886-ip-m1.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 2 · Assets, liabilities and consolidation", "title": "Intermediate Paper 1 · Advanced Accounting · Module 2", "source": "https://resource.cdn.icai.org/93667bos-aps5886-ip-m2.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 3 · Company financial statements", "title": "Intermediate Paper 1 · Advanced Accounting · Module 3", "source": "https://resource.cdn.icai.org/93491bos-aps5886-ip-m3.pdf"},
    {"level": "CA Intermediate", "subject": "Corporate and Other Laws", "chapter": "Companies Act and other laws", "title": "Intermediate Paper 2 · Corporate and Other Laws", "source": "https://www.icai.org/post/sm-intermediate-paper2"},
    {"level": "CA Intermediate", "subject": "Taxation", "chapter": "Section A · Income-tax Law", "title": "Intermediate Paper 3 · Taxation · Income-tax Law", "source": "https://www.icai.org/post/sm-intermediate-paper3-seca"},
    {"level": "CA Intermediate", "subject": "Taxation", "chapter": "Section B · Goods and Services Tax", "title": "Intermediate Paper 3 · Taxation · GST", "source": "https://www.icai.org/post/sm-intermediate-paper3-secb"},
    {"level": "CA Intermediate", "subject": "Cost and Management Accounting", "chapter": "Complete paper and latest applicable material", "title": "Intermediate Paper 4 · Cost and Management Accounting", "source": "https://www.icai.org/post/sm-intermediate-paper4"},
    {"level": "CA Intermediate", "subject": "Auditing and Ethics", "chapter": "Complete paper and latest applicable material", "title": "Intermediate Paper 5 · Auditing and Ethics", "source": "https://www.icai.org/post/sm-intermediate-paper5"},
    {"level": "CA Intermediate", "subject": "Financial Management", "chapter": "Section A · Financial Management", "title": "Intermediate Paper 6 · Financial Management", "source": "https://www.icai.org/post/sm-intermediate-paper6a"},
    {"level": "CA Intermediate", "subject": "Strategic Management", "chapter": "Section B · Strategic Management", "title": "Intermediate Paper 6 · Strategic Management", "source": "https://www.icai.org/post/sm-intermediate-paper6b"},
    {"level": "CA Intermediate", "subject": "Model Test Papers", "chapter": "Intermediate Group 1 and Group 2", "title": "Intermediate · Model Test Papers", "source": "https://resource.cdn.icai.org/84775bos68244-gp1.pdf"},
    {"level": "CA Final", "subject": "Financial Reporting", "chapter": "Group I · Paper 1", "title": "Final Paper 1 · Financial Reporting", "source": "https://www.icai.org/post/sm-final-paper1"},
    {"level": "CA Final", "subject": "Advanced Financial Management", "chapter": "Group I · Paper 2", "title": "Final Paper 2 · Advanced Financial Management", "source": "https://www.icai.org/post/sm-final-paper2"},
    {"level": "CA Final", "subject": "Advanced Auditing", "chapter": "Group I · Paper 3", "title": "Final Paper 3 · Advanced Auditing and Assurance", "source": "https://www.icai.org/post/sm-final-paper3"},
    {"level": "CA Final", "subject": "Direct Tax Laws", "chapter": "Group II · Paper 4", "title": "Final Paper 4 · Direct Tax Laws and International Taxation", "source": "https://www.icai.org/post/sm-final-paper4"},
    {"level": "CA Final", "subject": "Indirect Tax Laws", "chapter": "Group II · Paper 5", "title": "Final Paper 5 · Indirect Tax Laws", "source": "https://www.icai.org/post/sm-final-paper5"},
    {"level": "CA Final", "subject": "Integrated Business Solutions", "chapter": "Group II · Paper 6", "title": "Final Paper 6 · Integrated Business Solutions", "source": "https://www.icai.org/post.html?post_id=19442"},
    {"level": "CA Final", "subject": "Model Test Papers", "chapter": "Group I", "title": "Final · Model Test Papers · Group I", "source": "https://resource.cdn.icai.org/84556bos68130-final-gp1.pdf"},
    {"level": "CA Final", "subject": "Model Test Papers", "chapter": "Group II", "title": "Final · Model Test Papers · Group II", "source": "https://resource.cdn.icai.org/84557bos68130-final-gp2.pdf"},
    {"level": "CA Final", "subject": "SPOM · Set A", "chapter": "Corporate and Economic Laws", "title": "Self-Paced Online Modules · Set A", "source": "https://www.icai.org/post/bos-exam-spom-set-a"},
    {"level": "CA Final", "subject": "SPOM · Set B", "chapter": "Strategic Cost and Performance Management", "title": "Self-Paced Online Modules · Set B", "source": "https://www.icai.org/post/self-paced-online-modules-set-b-nset"},
    {"level": "CA Final", "subject": "SPOM · Set C", "chapter": "Risk Management, Sustainability, Public Finance and specialised papers", "title": "Self-Paced Online Modules · Set C", "source": "https://www.icai.org/post/self-paced-online-modules-nset"},
    {"level": "CA Final", "subject": "SPOM · Set D", "chapter": "Constitution, Psychology, Entrepreneurship and Digital Ecosystem", "title": "Self-Paced Online Modules · Set D", "source": "https://www.icai.org/post/self-paced-online-modules-nset"},
)


# Direct, current chapter/unit PDFs linked from the latest ICAI module pages. These
# are links only; CA OS does not download, copy or mirror ICAI material.
ICAI_CATALOG = ICAI_CATALOG + (
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 1 · Chapter 1 · Unit 1 · Meaning and Scope of Accounting", "title": "Foundation Accounting · Ch 1 · Unit 1", "source": "https://resource.cdn.icai.org/93935bos-aps6170-ch1u1.pdf"},
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 1 · Chapter 1 · Unit 2 · Accounting Concepts, Principles and Conventions", "title": "Foundation Accounting · Ch 1 · Unit 2", "source": "https://resource.cdn.icai.org/93936bos-aps6170-ch1u2.pdf"},
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 1 · Chapter 1 · Unit 3 · Capital and Revenue Expenditures and Receipts", "title": "Foundation Accounting · Ch 1 · Unit 3", "source": "https://resource.cdn.icai.org/93937bos-aps6170-ch1u3.pdf"},
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 1 · Chapter 1 · Unit 4 · Contingent Assets and Contingent Liabilities", "title": "Foundation Accounting · Ch 1 · Unit 4", "source": "https://resource.cdn.icai.org/93938bos-aps6170-ch1u4.pdf"},
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 1 · Chapter 1 · Unit 5 · Accounting Policies", "title": "Foundation Accounting · Ch 1 · Unit 5", "source": "https://resource.cdn.icai.org/93939bos-aps6170-ch1u5.pdf"},
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 1 · Chapter 1 · Unit 6 · Valuation Principles and Accounting Estimates", "title": "Foundation Accounting · Ch 1 · Unit 6", "source": "https://resource.cdn.icai.org/93940bos-aps6170-ch1u6.pdf"},
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 1 · Chapter 1 · Unit 7 · Accounting Standards", "title": "Foundation Accounting · Ch 1 · Unit 7", "source": "https://resource.cdn.icai.org/93941bos-aps6170-ch1u7.pdf"},
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 1 · Chapter 2 · Unit 1 · Basic Accounting Procedures", "title": "Foundation Accounting · Ch 2 · Unit 1", "source": "https://resource.cdn.icai.org/93942bos-aps6170-ch2u1.pdf"},
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 1 · Chapter 2 · Unit 2 · Ledgers", "title": "Foundation Accounting · Ch 2 · Unit 2", "source": "https://resource.cdn.icai.org/93943bos-aps6170-ch2u2.pdf"},
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 1 · Chapter 2 · Unit 3 · Trial Balance", "title": "Foundation Accounting · Ch 2 · Unit 3", "source": "https://resource.cdn.icai.org/93944bos-aps6170-ch2u3.pdf"},
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 1 · Chapter 2 · Unit 4 · Subsidiary Books", "title": "Foundation Accounting · Ch 2 · Unit 4", "source": "https://resource.cdn.icai.org/93945bos-aps6170-ch2u4.pdf"},
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 1 · Chapter 2 · Unit 5 · Cash Book", "title": "Foundation Accounting · Ch 2 · Unit 5", "source": "https://resource.cdn.icai.org/93946bos-aps6170-ch2u5.pdf"},
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 1 · Chapter 2 · Unit 6 · Rectification of Errors", "title": "Foundation Accounting · Ch 2 · Unit 6", "source": "https://resource.cdn.icai.org/93954bos-aps6170-ch2u6.pdf"},
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 1 · Chapter 3 · Bank Reconciliation Statement", "title": "Foundation Accounting · Chapter 3", "source": "https://resource.cdn.icai.org/93955bos-aps6170-ch3.pdf"},
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 1 · Chapter 4 · Inventories", "title": "Foundation Accounting · Chapter 4", "source": "https://resource.cdn.icai.org/93956bos-aps6170-ch4.pdf"},
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 1 · Chapter 5 · Depreciation and Amortisation", "title": "Foundation Accounting · Chapter 5", "source": "https://resource.cdn.icai.org/93957bos-aps6170-ch5.pdf"},
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 1 · Chapter 6 · Bills of Exchange and Promissory Notes", "title": "Foundation Accounting · Chapter 6", "source": "https://resource.cdn.icai.org/93958bos-aps6170-ch6.pdf"},
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 1 · Chapter 7 · Unit 1 · Final Accounts of Non-Manufacturing Entities", "title": "Foundation Accounting · Ch 7 · Unit 1", "source": "https://resource.cdn.icai.org/93959bos-aps6170-ch7u1.pdf"},
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 1 · Chapter 7 · Unit 2 · Final Accounts of Manufacturing Entities", "title": "Foundation Accounting · Ch 7 · Unit 2", "source": "https://resource.cdn.icai.org/93960bos-aps6170-ch7u2.pdf"},
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 2 · Chapter 8 · Financial Statements of Not-for-Profit Organisations", "title": "Foundation Accounting · Chapter 8", "source": "https://resource.cdn.icai.org/94004bos-aps6170-ch8.pdf"},
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 2 · Chapter 9 · Accounts from Incomplete Records", "title": "Foundation Accounting · Chapter 9", "source": "https://resource.cdn.icai.org/94005bos-aps6170-ch9.pdf"},
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 2 · Chapter 10 · Partnership and LLP Accounts · Unit 1", "title": "Foundation Accounting · Ch 10 · Unit 1", "source": "https://resource.cdn.icai.org/94007bos-aps6170-ch10u1.pdf"},
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 2 · Chapter 10 · Partnership and LLP Accounts · Unit 2", "title": "Foundation Accounting · Ch 10 · Unit 2", "source": "https://resource.cdn.icai.org/94008bos-aps6170-ch10u2.pdf"},
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 2 · Chapter 10 · Partnership and LLP Accounts · Unit 3", "title": "Foundation Accounting · Ch 10 · Unit 3", "source": "https://resource.cdn.icai.org/94009bos-aps6170-ch10u3.pdf"},
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 2 · Chapter 10 · Partnership and LLP Accounts · Unit 4", "title": "Foundation Accounting · Ch 10 · Unit 4", "source": "https://resource.cdn.icai.org/94010bos-aps6170-ch10u4.pdf"},
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 2 · Chapter 10 · Partnership and LLP Accounts · Unit 5", "title": "Foundation Accounting · Ch 10 · Unit 5", "source": "https://resource.cdn.icai.org/94011bos-aps6170-ch10u5.pdf"},
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 2 · Chapter 10 · Partnership and LLP Accounts · Unit 6", "title": "Foundation Accounting · Ch 10 · Unit 6", "source": "https://resource.cdn.icai.org/94012bos-aps6170-ch10u6.pdf"},
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 2 · Chapter 11 · Company Accounts · Unit 1", "title": "Foundation Accounting · Ch 11 · Unit 1", "source": "https://resource.cdn.icai.org/94013bos-aps6170-ch11u1.pdf"},
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 2 · Chapter 11 · Company Accounts · Unit 2", "title": "Foundation Accounting · Ch 11 · Unit 2", "source": "https://resource.cdn.icai.org/94014bos-aps6170-ch11u2.pdf"},
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 2 · Chapter 11 · Company Accounts · Unit 3", "title": "Foundation Accounting · Ch 11 · Unit 3", "source": "https://resource.cdn.icai.org/94015bos-aps6170-ch11u3.pdf"},
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 2 · Chapter 11 · Company Accounts · Unit 4", "title": "Foundation Accounting · Ch 11 · Unit 4", "source": "https://resource.cdn.icai.org/94016bos-aps6170-ch11u4.pdf"},
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 2 · Chapter 11 · Company Accounts · Unit 5", "title": "Foundation Accounting · Ch 11 · Unit 5", "source": "https://resource.cdn.icai.org/94021bos-aps6170-ch11u5.pdf"},
    {"level": "CA Foundation", "subject": "Accounting", "chapter": "Module 2 · Chapter 11 · Company Accounts · Unit 6", "title": "Foundation Accounting · Ch 11 · Unit 6", "source": "https://resource.cdn.icai.org/94022bos-aps6170-ch11u6.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 1 · Chapter 1 · Introduction to Accounting Standards", "title": "Intermediate Advanced Accounting · Chapter 1", "source": "https://resource.cdn.icai.org/93350bos-aps5886-ch1.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 1 · Chapter 2 · Framework for Preparation and Presentation of Financial Statements", "title": "Intermediate Advanced Accounting · Chapter 2", "source": "https://resource.cdn.icai.org/93351bos-aps5886-ch2.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 1 · Chapter 3 · Applicability of Accounting Standards", "title": "Intermediate Advanced Accounting · Chapter 3", "source": "https://resource.cdn.icai.org/93352bos-aps5886-ch3.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 1 · Chapter 4 · Presentation and Disclosures · Unit 1", "title": "Intermediate Advanced Accounting · Ch 4 · Unit 1", "source": "https://resource.cdn.icai.org/93353bos-aps5886-ch4u1.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 1 · Chapter 4 · Presentation and Disclosures · Unit 2", "title": "Intermediate Advanced Accounting · Ch 4 · Unit 2", "source": "https://resource.cdn.icai.org/93354bos-aps5886-ch4u2.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 1 · Chapter 4 · Presentation and Disclosures · Unit 3", "title": "Intermediate Advanced Accounting · Ch 4 · Unit 3", "source": "https://resource.cdn.icai.org/93355bos-aps5886-ch4u3.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 1 · Chapter 4 · Presentation and Disclosures · Unit 4", "title": "Intermediate Advanced Accounting · Ch 4 · Unit 4", "source": "https://resource.cdn.icai.org/93356bos-aps5886-ch4u4.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 1 · Chapter 4 · Presentation and Disclosures · Unit 5", "title": "Intermediate Advanced Accounting · Ch 4 · Unit 5", "source": "https://resource.cdn.icai.org/93357bos-aps5886-ch4u5.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 1 · Chapter 4 · Presentation and Disclosures · Unit 6", "title": "Intermediate Advanced Accounting · Ch 4 · Unit 6", "source": "https://resource.cdn.icai.org/93358bos-aps5886-ch4u6.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 1 · Chapter 4 · Presentation and Disclosures · Unit 7", "title": "Intermediate Advanced Accounting · Ch 4 · Unit 7", "source": "https://resource.cdn.icai.org/93359bos-aps5886-ch4u7.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 2 · Chapter 5 · Assets Based Accounting Standards · Unit 1", "title": "Intermediate Advanced Accounting · Ch 5 · Unit 1", "source": "https://resource.cdn.icai.org/93641bos-aps5886-ch5u1.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 2 · Chapter 5 · Assets Based Accounting Standards · Unit 2", "title": "Intermediate Advanced Accounting · Ch 5 · Unit 2", "source": "https://resource.cdn.icai.org/93642bos-aps5886-ch5u2.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 2 · Chapter 5 · Assets Based Accounting Standards · Unit 3", "title": "Intermediate Advanced Accounting · Ch 5 · Unit 3", "source": "https://resource.cdn.icai.org/93643bos-aps5886-ch5u3.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 2 · Chapter 5 · Assets Based Accounting Standards · Unit 4", "title": "Intermediate Advanced Accounting · Ch 5 · Unit 4", "source": "https://resource.cdn.icai.org/93644bos-aps5886-ch5u4.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 2 · Chapter 5 · Assets Based Accounting Standards · Unit 5", "title": "Intermediate Advanced Accounting · Ch 5 · Unit 5", "source": "https://resource.cdn.icai.org/93645bos-aps5886-ch5u5.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 2 · Chapter 5 · Assets Based Accounting Standards · Unit 6", "title": "Intermediate Advanced Accounting · Ch 5 · Unit 6", "source": "https://resource.cdn.icai.org/93646bos-aps5886-ch5u6.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 2 · Chapter 5 · Assets Based Accounting Standards · Unit 7", "title": "Intermediate Advanced Accounting · Ch 5 · Unit 7", "source": "https://resource.cdn.icai.org/93647bos-aps5886-ch5u7.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 2 · Chapter 6 · Liabilities Based Accounting Standards · Unit 1", "title": "Intermediate Advanced Accounting · Ch 6 · Unit 1", "source": "https://resource.cdn.icai.org/93648bos-aps5886-ch6u1.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 2 · Chapter 6 · Liabilities Based Accounting Standards · Unit 2", "title": "Intermediate Advanced Accounting · Ch 6 · Unit 2", "source": "https://resource.cdn.icai.org/93649bos-aps5886-ch6u2.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 2 · Chapter 7 · Accounting Standards Impacting Financial Statements · Unit 1", "title": "Intermediate Advanced Accounting · Ch 7 · Unit 1", "source": "https://resource.cdn.icai.org/93650bos-aps5886-ch7u1.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 2 · Chapter 7 · Accounting Standards Impacting Financial Statements · Unit 2", "title": "Intermediate Advanced Accounting · Ch 7 · Unit 2", "source": "https://resource.cdn.icai.org/93651bos-aps5886-ch7u2.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 2 · Chapter 7 · Accounting Standards Impacting Financial Statements · Unit 3", "title": "Intermediate Advanced Accounting · Ch 7 · Unit 3", "source": "https://resource.cdn.icai.org/93652bos-aps5886-ch7u3.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 2 · Chapter 7 · Accounting Standards Impacting Financial Statements · Unit 4", "title": "Intermediate Advanced Accounting · Ch 7 · Unit 4", "source": "https://resource.cdn.icai.org/93653bos-aps5886-ch7u4.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 2 · Chapter 8 · Revenue Based Accounting Standards · Unit 1", "title": "Intermediate Advanced Accounting · Ch 8 · Unit 1", "source": "https://resource.cdn.icai.org/93654bos-aps5886-ch8u1.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 2 · Chapter 8 · Revenue Based Accounting Standards · Unit 2", "title": "Intermediate Advanced Accounting · Ch 8 · Unit 2", "source": "https://resource.cdn.icai.org/93655bos-aps5886-ch8u2.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 2 · Chapter 9 · Other Accounting Standards · Unit 1", "title": "Intermediate Advanced Accounting · Ch 9 · Unit 1", "source": "https://resource.cdn.icai.org/93662bos-aps5886-ch9u1.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 2 · Chapter 9 · Other Accounting Standards · Unit 2", "title": "Intermediate Advanced Accounting · Ch 9 · Unit 2", "source": "https://resource.cdn.icai.org/93663bos-aps5886-ch9u2.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 2 · Chapter 10 · Consolidated Financial Statements · Unit 1", "title": "Intermediate Advanced Accounting · Ch 10 · Unit 1", "source": "https://resource.cdn.icai.org/93664bos-aps5886-ch10u1.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 2 · Chapter 10 · Consolidated Financial Statements · Unit 2", "title": "Intermediate Advanced Accounting · Ch 10 · Unit 2", "source": "https://resource.cdn.icai.org/93665bos-aps5886-ch10u2.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 2 · Chapter 10 · Consolidated Financial Statements · Unit 3", "title": "Intermediate Advanced Accounting · Ch 10 · Unit 3", "source": "https://resource.cdn.icai.org/93666bos-aps5886-ch10u3.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 3 · Chapter 11 · Financial Statements of Companies · Unit 1", "title": "Intermediate Advanced Accounting · Ch 11 · Unit 1", "source": "https://resource.cdn.icai.org/93484bos-aps5886-ch11u1.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 3 · Chapter 11 · Financial Statements of Companies · Unit 2", "title": "Intermediate Advanced Accounting · Ch 11 · Unit 2", "source": "https://resource.cdn.icai.org/93485bos-aps5886-ch11u2.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 3 · Chapter 12 · Buyback of Securities", "title": "Intermediate Advanced Accounting · Chapter 12", "source": "https://resource.cdn.icai.org/93487bos-aps5886-ch12.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 3 · Chapter 13 · Amalgamation of Companies", "title": "Intermediate Advanced Accounting · Chapter 13", "source": "https://resource.cdn.icai.org/93488bos-aps5886-ch13.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 3 · Chapter 14 · Internal Reconstruction", "title": "Intermediate Advanced Accounting · Chapter 14", "source": "https://resource.cdn.icai.org/93489bos-aps5886-ch14.pdf"},
    {"level": "CA Intermediate", "subject": "Advanced Accounting", "chapter": "Module 3 · Chapter 15 · Accounting for Branches including Foreign Branches", "title": "Intermediate Advanced Accounting · Chapter 15", "source": "https://resource.cdn.icai.org/93490bos-aps5886-ch15.pdf"},
)


def _chapter_items(level: str, subject: str, title_prefix: str, entries: tuple[tuple[str, str], ...]) -> tuple[dict[str, str], ...]:
    return tuple(
        {
            "level": level,
            "subject": subject,
            "chapter": chapter,
            "title": f"{title_prefix} · {chapter.split(' · ', 1)[-1]}",
            "source": source,
        }
        for chapter, source in entries
    )


ICAI_CATALOG = ICAI_CATALOG + _chapter_items(
    "CA Foundation",
    "Business Laws",
    "Foundation Business Laws",
    (
        ("Initial Pages", "https://resource.cdn.icai.org/93741bos-aps6083-p2-ip.pdf"),
        ("Chapter 1 · Indian Regulatory Framework", "https://resource.cdn.icai.org/93742bos-aps6083-p2-ch1.pdf"),
        ("Chapter 2 · The Indian Contract Act · Unit 1 · Nature of Contracts", "https://resource.cdn.icai.org/93743bos-aps6083-p2-ch2u1.pdf"),
        ("Chapter 2 · The Indian Contract Act · Unit 2 · Consideration", "https://resource.cdn.icai.org/93744bos-aps6083-p2-ch2u2.pdf"),
        ("Chapter 2 · The Indian Contract Act · Unit 3 · Other Essential Elements of a Contract", "https://resource.cdn.icai.org/93745bos-aps6083-p2-ch2u3.pdf"),
        ("Chapter 2 · The Indian Contract Act · Unit 4 · Performance of Contract", "https://resource.cdn.icai.org/93746bos-aps6083-p2-ch2u4.pdf"),
        ("Chapter 2 · The Indian Contract Act · Unit 5 · Breach of Contract and its Remedies", "https://resource.cdn.icai.org/93747bos-aps6083-p2-ch2u5.pdf"),
        ("Chapter 2 · The Indian Contract Act · Unit 6 · Contingent and Quasi Contracts", "https://resource.cdn.icai.org/93748bos-aps6083-p2-ch2u6.pdf"),
        ("Chapter 2 · The Indian Contract Act · Unit 7 · Indemnity and Guarantee", "https://resource.cdn.icai.org/93749bos-aps6083-p2-ch2u7.pdf"),
        ("Chapter 2 · The Indian Contract Act · Unit 8 · Bailment and Pledge", "https://resource.cdn.icai.org/93750bos-aps6083-p2-ch2u8.pdf"),
        ("Chapter 2 · The Indian Contract Act · Unit 9 · Agency", "https://resource.cdn.icai.org/93751bos-aps6083-p2-ch2u9.pdf"),
        ("Chapter 3 · The Sale of Goods Act", "https://resource.cdn.icai.org/93752bos-aps6083-p2-ch3u1.pdf"),
        ("Chapter 4 · The Indian Partnership Act · Unit 1", "https://resource.cdn.icai.org/93756bos-aps6083-p2-ch4u1.pdf"),
        ("Chapter 4 · The Indian Partnership Act · Unit 2", "https://resource.cdn.icai.org/93757bos-aps6083-p2-ch4u2.pdf"),
        ("Chapter 4 · The Indian Partnership Act · Unit 3", "https://resource.cdn.icai.org/93758bos-aps6083-p2-ch4u3.pdf"),
        ("Chapter 5 · Limited Liability Partnership Act", "https://resource.cdn.icai.org/93759bos-aps6083-p2-ch5.pdf"),
        ("Chapter 6 · Companies Act", "https://resource.cdn.icai.org/93760bos-aps6083-p2-ch6.pdf"),
        ("Chapter 7 · Negotiable Instruments Act", "https://resource.cdn.icai.org/93761bos-aps6083-p2-ch7.pdf"),
    ),
) + _chapter_items(
    "CA Intermediate",
    "Corporate and Other Laws",
    "Intermediate Corporate Laws",
    (
        ("Module 1 · Chapter 1 · Preliminary", "https://resource.cdn.icai.org/93466bos-aps5940-p2-ch1.pdf"),
        ("Module 1 · Chapter 2 · Incorporation of Company", "https://resource.cdn.icai.org/93467bos-aps5940-p2-ch2.pdf"),
        ("Module 1 · Chapter 3 · Prospectus and Allotment of Securities", "https://resource.cdn.icai.org/93468bos-aps5940-p2-ch3.pdf"),
        ("Module 1 · Chapter 4 · Share Capital and Debentures", "https://resource.cdn.icai.org/93469bos-aps5940-p2-ch4.pdf"),
        ("Module 1 · Chapter 5 · Acceptance of Deposits by Companies", "https://resource.cdn.icai.org/93470bos-aps5940-p2-ch5.pdf"),
        ("Module 1 · Chapter 6 · Registration of Charges", "https://resource.cdn.icai.org/93471bos-aps5940-p2-ch6.pdf"),
        ("Module 2 · Chapter 7 · Management and Administration", "https://resource.cdn.icai.org/93472bos-aps5940-p2-ch7.pdf"),
        ("Module 2 · Chapter 8 · Declaration and Payment of Dividend", "https://resource.cdn.icai.org/93473bos-aps5940-p2-ch8.pdf"),
        ("Module 2 · Chapter 9 · Accounts of Companies", "https://resource.cdn.icai.org/93474bos-aps5940-p2-ch9.pdf"),
        ("Module 2 · Chapter 10 · Audit and Auditors", "https://resource.cdn.icai.org/93475bos-aps5940-p2-ch10.pdf"),
        ("Module 2 · Chapter 11 · Companies Incorporated Outside India", "https://resource.cdn.icai.org/93476bos-aps5940-p2-ch11.pdf"),
        ("Module 3 · Chapter 12 · Limited Liability Partnership Act", "https://resource.cdn.icai.org/93477bos-aps5940-p2-ch12.pdf"),
        ("Other Laws · Chapter 1 · General Clauses Act", "https://resource.cdn.icai.org/93481bos-aps5940-p2-olc1.pdf"),
        ("Other Laws · Chapter 2 · Interpretation of Statutes", "https://resource.cdn.icai.org/93482bos-aps5940-p2-olc2.pdf"),
        ("Other Laws · Chapter 3 · Foreign Exchange Management Act", "https://resource.cdn.icai.org/93483bos-aps5940-p2-olc3.pdf"),
    ),
) + _chapter_items(
    "CA Intermediate",
    "Taxation",
    "Intermediate Taxation",
    (
        ("Income-tax · Module 1 · Chapter 1 · Basic Concepts", "https://resource.cdn.icai.org/93394bos-aps5909-ch1.pdf"),
        ("Income-tax · Module 1 · Chapter 2 · Residential Status and Scope of Total Income", "https://resource.cdn.icai.org/93395bos-aps5909-ch2.pdf"),
        ("Income-tax · Module 1 · Chapter 3 · Unit 1 · Salaries", "https://resource.cdn.icai.org/93396bos-aps5909-ch3u1.pdf"),
        ("Income-tax · Module 1 · Chapter 3 · Unit 2 · Income from House Property", "https://resource.cdn.icai.org/93397bos-aps5909-ch3u2.pdf"),
        ("Income-tax · Module 1 · Chapter 3 · Unit 3 · Profits and Gains of Business or Profession", "https://resource.cdn.icai.org/93398bos-aps5909-ch3u3.pdf"),
        ("Income-tax · Module 1 · Chapter 3 · Unit 4 · Capital Gains", "https://resource.cdn.icai.org/93399bos-aps5909-ch3u4.pdf"),
        ("Income-tax · Module 1 · Chapter 3 · Unit 5 · Income from Other Sources", "https://resource.cdn.icai.org/93400bos-aps5909-ch3u5.pdf"),
        ("Income-tax · Module 2 · Chapter 4 · Income of Other Persons", "https://resource.cdn.icai.org/93401bos-aps5909-ch4.pdf"),
        ("Income-tax · Module 2 · Chapter 5 · Set-Off or Carry Forward of Losses", "https://resource.cdn.icai.org/93402bos-aps5909-ch5.pdf"),
        ("Income-tax · Module 2 · Chapter 6 · Deductions from Gross Total Income", "https://resource.cdn.icai.org/93403bos-aps5909-ch6.pdf"),
        ("Income-tax · Module 2 · Chapter 7 · Tax Deduction or Collection at Source", "https://resource.cdn.icai.org/93465bos-aps5909-ch7.pdf"),
        ("Income-tax · Module 2 · Chapter 8 · Filing Return of Income and Self Assessment", "https://resource.cdn.icai.org/93404bos-aps5909-ch8.pdf"),
        ("Income-tax · Module 2 · Chapter 9 · Income Tax Liability", "https://resource.cdn.icai.org/93405bos-aps5909-ch9.pdf"),
        ("GST · Module 1 · Chapter 1 · GST in India", "https://resource.cdn.icai.org/93618bos-aps6021-p3b-may2027-ch1.pdf"),
        ("GST · Module 1 · Chapter 2 · Supply under GST", "https://resource.cdn.icai.org/93619bos-aps6021-p3b-may2027-ch2.pdf"),
        ("GST · Module 1 · Chapter 3 · Charge of GST", "https://resource.cdn.icai.org/93620bos-aps6021-p3b-may2027-ch3.pdf"),
        ("GST · Module 1 · Chapter 4 · Place of Supply", "https://resource.cdn.icai.org/93621bos-aps6021-p3b-may2027-ch4.pdf"),
        ("GST · Module 1 · Chapter 5 · Exemptions from GST", "https://resource.cdn.icai.org/93622bos-aps6021-p3b-may2027-ch5.pdf"),
        ("GST · Module 1 · Chapter 6 · Time of Supply", "https://resource.cdn.icai.org/93623bos-aps6021-p3b-may2027-ch6.pdf"),
        ("GST · Module 1 · Chapter 7 · Value of Supply", "https://resource.cdn.icai.org/93624bos-aps6021-p3b-may2027-ch7.pdf"),
        ("GST · Module 2 · Chapter 8 · Input Tax Credit", "https://resource.cdn.icai.org/93797bos-aps6021-p3b-may2027-ch8.pdf"),
        ("GST · Module 2 · Chapter 9 · Registration", "https://resource.cdn.icai.org/93798bos-aps6021-p3b-may2027-ch9.pdf"),
        ("GST · Module 2 · Chapter 10 · Tax Invoice, Credit and Debit Notes", "https://resource.cdn.icai.org/93799bos-aps6021-p3b-may2027-ch10.pdf"),
        ("GST · Module 2 · Chapter 11 · Accounts and Records", "https://resource.cdn.icai.org/93800bos-aps6021-p3b-may2027-ch11.pdf"),
        ("GST · Module 2 · Chapter 12 · E-Way Bill", "https://resource.cdn.icai.org/93801bos-aps6021-p3b-may2027-ch12.pdf"),
        ("GST · Module 2 · Chapter 13 · Payment of Tax", "https://resource.cdn.icai.org/93802bos-aps6021-p3b-may2027-ch13.pdf"),
        ("GST · Module 2 · Chapter 14 · Tax Deduction or Collection of Tax", "https://resource.cdn.icai.org/93803bos-aps6021-p3b-may2027-ch14.pdf"),
        ("GST · Module 2 · Chapter 15 · Returns", "https://resource.cdn.icai.org/93804bos-aps6021-p3b-may2027-ch15.pdf"),
    ),
)
