"use client";

import type { Route } from "next";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Icon } from "@/components/icon";
import { apiFetch, ApiError, API_BASE_URL } from "@/lib/api-client";

type ResourceItem = {
  id: string;
  title: string;
  description?: string | null;
  level: string;
  subject: string;
  chapter?: string | null;
  resource_type: string;
  attempt?: string | null;
  year?: number | null;
  file_name?: string | null;
  file_size?: number | null;
  official_icai: boolean;
  bookmarked: boolean;
  completed: boolean;
  created_at: string;
};

const pageCopy: Record<string, { eyebrow: string; title: string; body: string; icon: string }> = {
  mcq: { eyebrow: "Practice with intent", title: "Build accuracy, one question at a time.", body: "Switch between chapter practice and your personal mistake book without losing your rhythm.", icon: "circle-help" },
  tests: { eyebrow: "Assessments", title: "Tests that tell you what to do next.", body: "Take timed tests, review your attempt and turn feedback into your next study block.", icon: "clipboard-check" },
  syllabus: { eyebrow: "Your progress", title: "See the syllabus move.", body: "Track every chapter from first read to final revision and keep the whole attempt visible.", icon: "chart-no-axes-combined" },
  planner: { eyebrow: "Study planner", title: "Make a plan you can actually keep.", body: "Shape your week around available hours, weak subjects and the exam date ahead.", icon: "calendar-days" },
  revision: { eyebrow: "Spaced revision", title: "Return at the right moment.", body: "Your revision queue brings important chapters back before they fade.", icon: "rotate-ccw" },
  videos: { eyebrow: "Video learning", title: "Learn at your pace.", body: "Keep lectures, marathons and quick concept refreshers in one focused place.", icon: "play-square" },
  "past-papers": { eyebrow: "Past paper analysis", title: "Study the pattern, not the prediction.", body: "Explore chapter frequency and marks distribution as preparation signals, never guarantees.", icon: "scan-search" },
  library: { eyebrow: "Your library", title: "Everything worth coming back to.", body: "Bookmarks, saved questions and completed resources stay close to your next session.", icon: "bookmark" },
  queries: { eyebrow: "Faculty support", title: "A clearer answer is one question away.", body: "Ask a structured doubt, add context and keep the reply with the chapter it belongs to.", icon: "message-circle" },
  ai: { eyebrow: "AI zone", title: "A study assistant with boundaries.", body: "Ask for explanations and revision help. Official rules and provisions always need a cited source.", icon: "sparkles" },
  articleship: { eyebrow: "Articleship", title: "Find the next place to grow.", body: "Explore opportunities, save promising roles and keep your applications organised.", icon: "briefcase-business" },
  career: { eyebrow: "Career", title: "Make your options concrete.", body: "Browse paths, skill roadmaps and practical next steps beyond the exam hall.", icon: "compass" },
  "icai-updates": { eyebrow: "Official updates", title: "Stay close to the source.", body: "Important exam, BOS and training updates with links back to the original official source.", icon: "landmark" },
  notifications: { eyebrow: "Notification centre", title: "Nothing important gets lost.", body: "Review test reminders, query responses and revision nudges in one calm feed.", icon: "bell" },
  profile: { eyebrow: "Your profile", title: "Keep your attempt details current.", body: "Your level, group and preferences help the platform recommend more useful work.", icon: "user-round" },
  settings: { eyebrow: "Workspace settings", title: "Make CA OS work your way.", body: "Manage theme, reminders, sessions and the details that shape your workspace.", icon: "settings" },
  timetable: { eyebrow: "Your calendar", title: "See the week at a glance.", body: "Classes, tests, live sessions and revisions in one timetable.", icon: "calendar-check" },
};

function FeatureHeader({ copy, action, onAction }: { copy: typeof pageCopy[string]; action?: string; onAction?: () => void }) {
  return <section className="feature-hero"><div><div className="eyebrow feature-eyebrow"><span className="feature-eyebrow-icon"><Icon name={copy.icon} size={14} /></span>{copy.eyebrow}</div><h1>{copy.title}</h1><p>{copy.body}</p></div>{action ? <button className="button button-primary button-with-icon" onClick={onAction}><Icon name="plus" size={16} /> {action}</button> : null}</section>;
}

function FilterChip({ active, children, onClick }: { active: boolean; children: React.ReactNode; onClick: () => void }) {
  return <button className={`filter-chip ${active ? "filter-chip-active" : ""}`} onClick={onClick}>{children}</button>;
}

function EmptyState({ icon, title, body, href, action }: { icon: string; title: string; body: string; href?: string; action?: string }) {
  return <div className="empty-state"><div className="empty-state-icon"><Icon name={icon} size={22} /></div><h3>{title}</h3><p>{body}</p>{href && action ? <Link href={href as Route} className="button button-primary">{action}<Icon name="arrow-right" size={14} /></Link> : null}</div>;
}

function ResourceWorkspace() {
  const [resources, setResources] = useState<ResourceItem[]>([]);
  const [query, setQuery] = useState("");
  const [type, setType] = useState("All");
  const [loading, setLoading] = useState(true);
  const [notice, setNotice] = useState<string | null>(null);

  useEffect(() => {
    apiFetch<ResourceItem[]>("/api/v1/resources").then(setResources).catch(() => setResources([])).finally(() => setLoading(false));
  }, []);

  const types = ["All", ...Array.from(new Set(resources.map((resource) => resource.resource_type)))];
  const filtered = resources.filter((resource) => `${resource.title} ${resource.subject} ${resource.chapter ?? ""}`.toLowerCase().includes(query.toLowerCase()) && (type === "All" || resource.resource_type === type));
  const toggleBookmark = async (resource: ResourceItem) => {
    try { await apiFetch(`/api/v1/resources/${resource.id}/bookmark`, { method: "POST" }); setResources((current) => current.map((item) => item.id === resource.id ? { ...item, bookmarked: !item.bookmarked } : item)); setNotice(resource.bookmarked ? "Removed from your library" : "Saved to your library"); } catch (error) { setNotice(error instanceof ApiError ? error.message : "Could not update your library"); }
  };
  const complete = async (resource: ResourceItem) => {
    try { await apiFetch(`/api/v1/resources/${resource.id}/progress`, { method: "PATCH", body: JSON.stringify({ completed: !resource.completed }) }); setResources((current) => current.map((item) => item.id === resource.id ? { ...item, completed: !item.completed } : item)); } catch { setNotice("Could not update progress"); }
  };

  return <><div className="feature-toolbar"><div className="feature-search"><Icon name="search" size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search title, subject or chapter" /></div><Link href="/admin/resources" className="button button-primary button-with-icon"><Icon name="plus" size={15} /> Upload resource</Link></div><div className="filter-row">{types.map((item) => <FilterChip active={type === item} key={item} onClick={() => setType(item)}>{item}</FilterChip>)}</div>{notice ? <div className="inline-notice"><Icon name="check" size={15} /> {notice}</div> : null}{loading ? <div className="resource-grid">{[1, 2, 3].map((item) => <div className="skeleton-card" key={item} />)}</div> : filtered.length ? <div className="resource-grid">{filtered.map((resource) => <article className="resource-card" key={resource.id}><div className="resource-card-top"><div className="resource-file-icon"><Icon name="file-text" size={20} /></div><button className={`icon-button ${resource.bookmarked ? "icon-button-active" : ""}`} onClick={() => toggleBookmark(resource)} aria-label={resource.bookmarked ? "Remove bookmark" : "Bookmark resource"}><Icon name="bookmark" size={16} /></button></div><div className="resource-card-body"><div className="resource-type-line"><span>{resource.resource_type}</span>{resource.official_icai ? <span className="official-badge">Official source</span> : null}</div><h3>{resource.title}</h3><p>{resource.subject}{resource.chapter ? ` · ${resource.chapter}` : ""}</p></div><div className="resource-card-footer"><span>{resource.file_name ?? resource.attempt ?? "Resource"}</span><div className="resource-card-actions">{resource.file_name ? <button onClick={() => window.open(`${API_BASE_URL}/api/v1/resources/${resource.id}/download`, "_blank", "noopener,noreferrer")}><Icon name="download" size={13} /> Download</button> : null}<button className={resource.completed ? "completed-action" : ""} onClick={() => complete(resource)}>{resource.completed ? <><Icon name="check" size={13} /> Completed</> : "Mark complete"}</button></div></div></article>)}</div> : <EmptyState icon="book-open" title="Your resource shelf is ready." body="Once an admin uploads authorised study material, it will appear here with filters, bookmarks and progress tracking." href="/admin/resources" action="Open content manager" />}</>;
}

type McqItem = { id: string; prompt: string; options: string[]; subject: string; chapter?: string | null; difficulty: string };
type TestItem = { id: string; title: string; description?: string | null; duration_minutes: number; marks: number; question_count: number; status: string };
type SyllabusItem = { id: string; subject: string; chapter: string; total_topics: number; completed_topics: number; progress: number; status: string };
type PlanTask = { id: string; title: string; subject?: string | null; due_date: string; minutes: number; completed: boolean };
type RevisionItem = { id: string; title: string; subject?: string | null; due_at: string; status: string };
type QueryItem = { id: string; title: string; subject: string; body: string; answer?: string | null; status: string };

function McqWorkspace() {
  const [questions, setQuestions] = useState<McqItem[]>([]);
  const [index, setIndex] = useState(0);
  const [selected, setSelected] = useState<number | null>(null);
  const [result, setResult] = useState<{ correct: boolean; correct_option: number; explanation: string; score: number } | null>(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => { apiFetch<McqItem[]>("/api/v1/mcqs").then(setQuestions).catch(() => setQuestions([])).finally(() => setLoading(false)); }, []);
  if (loading) return <div className="practice-layout"><section className="practice-card"><div className="skeleton-card" /></section></div>;
  if (!questions.length) return <EmptyState icon="circle-help" title="Your practice bank is ready." body="An administrator needs to publish MCQs before practice can begin." href="/admin/mcqs" action="Open MCQ manager" />;
  const question = questions[index % questions.length];
  const submit = async () => { if (selected === null) return; try { const answer = await apiFetch<typeof result>(`/api/v1/mcqs/${question.id}/answer`, { method: "POST", body: JSON.stringify({ selected_option: selected }) }); setResult(answer); } catch { setResult(null); } };
  const next = () => { setIndex((current) => (current + 1) % questions.length); setSelected(null); setResult(null); };
  return <div className="practice-layout"><section className="practice-card"><div className="practice-meta"><span>Question {(index % questions.length) + 1} of {questions.length}</span><span>{question.chapter ?? question.subject}</span></div><div className="practice-progress"><span style={{ width: `${(((index % questions.length) + 1) / questions.length) * 100}%` }} /></div><h2>{question.prompt}</h2><div className="option-list">{question.options.map((option, optionIndex) => <button key={option} className={`option-row ${selected === optionIndex ? "option-selected" : ""} ${result && optionIndex === result.correct_option ? "option-correct" : ""} ${result && selected === optionIndex && !result.correct ? "option-wrong" : ""}`} onClick={() => !result && setSelected(optionIndex)}><span>{String.fromCharCode(65 + optionIndex)}</span>{option}{result && optionIndex === result.correct_option ? <Icon name="check" size={16} /> : null}</button>)}</div>{result ? <div className={`answer-explanation ${result.correct ? "answer-success" : "answer-error"}`}><strong>{result.correct ? "Correct. Keep that concept." : "Review this one before moving on."}</strong><p>{result.explanation}</p><small>Session accuracy: {result.score}%</small></div> : null}<div className="practice-actions">{result ? <button className="button button-primary" onClick={next}>Next question <Icon name="arrow-right" size={15} /></button> : <button className="button button-primary" onClick={submit} disabled={selected === null}>Submit answer</button>}<Link href="/mcq/mistakes" className="text-button">My mistakes <Icon name="arrow-right" size={14} /></Link></div></section><aside className="practice-side"><div className="mini-score"><span className="section-kicker">Live practice</span><strong>{result?.score ?? 0}%</strong><p>Your score is saved to the wrong-answer and analytics APIs.</p></div><div className="side-list"><span className="section-kicker">Practice modes</span><Link href="/mcq">Chapter wise <Icon name="arrow-right" size={14} /></Link><Link href="/mcq/mistakes">Wrong answers <Icon name="arrow-right" size={14} /></Link></div></aside></div>;
}

function TestsWorkspace() {
  const [tests, setTests] = useState<TestItem[]>([]);
  const [started, setStarted] = useState<string | null>(null);
  useEffect(() => { apiFetch<TestItem[]>("/api/v1/tests").then(setTests).catch(() => setTests([])); }, []);
  if (!tests.length) return <EmptyState icon="clipboard-check" title="Your test series is ready." body="An administrator needs to publish a test before it appears here." href="/admin/tests" action="Open test manager" />;
  return <div className="test-list">{tests.map((test) => <article className="test-card" key={test.id}><div className="test-card-icon"><Icon name="clipboard-check" size={20} /></div><div className="test-card-copy"><span className="section-kicker">{test.status}</span><h3>{test.title}</h3><p><span><Icon name="clock-3" size={13} /> {test.duration_minutes} min</span><span><Icon name="file-text" size={13} /> {test.marks} marks · {test.question_count} questions</span></p></div><div className="test-card-action">{started === test.id ? <span className="inline-status"><i /> Test opened</span> : <button className="button button-soft" onClick={() => setStarted(test.id)} disabled={test.status !== "open"}>{test.status !== "open" ? "Unavailable" : "Start test"}<Icon name="arrow-right" size={14} /></button>}</div></article>)}</div>;
}

function SyllabusWorkspace() {
  const [items, setItems] = useState<SyllabusItem[]>([]);
  useEffect(() => { apiFetch<SyllabusItem[]>("/api/v1/syllabus").then(setItems).catch(() => setItems([])); }, []);
  const update = async (item: SyllabusItem) => { const next = await apiFetch<SyllabusItem>(`/api/v1/syllabus/${item.id}`, { method: "PATCH", body: JSON.stringify({ completed_topics: Math.min(item.total_topics, item.completed_topics + 1), status: "in_progress" }) }); setItems((current) => current.map((candidate) => candidate.id === item.id ? next : candidate)); };
  const overall = items.length ? Math.round(items.reduce((sum, item) => sum + item.progress, 0) / items.length) : 0;
  return <div className="syllabus-layout"><section className="dashboard-card syllabus-overview"><div className="radial-progress"><span><strong>{overall}%</strong><small>overall</small></span></div><div><span className="section-kicker">Current attempt</span><h2>{items.filter((item) => item.progress > 0).length} of {items.length} chapters in motion.</h2><p>Progress is persisted to your syllabus tracker.</p></div></section><div className="subject-progress-grid">{items.map((item, index) => <article className="subject-progress-card" key={item.id}><div className={`subject-badge subject-${["violet", "coral", "blue", "mint"][index % 4]}`}>{item.subject.split(" ").map((word) => word[0]).join("").slice(0, 3)}</div><div className="subject-progress-copy"><div><h3>{item.subject}</h3><strong>{Math.round(item.progress)}%</strong></div><div className="progress-track"><span className={`progress-fill fill-${["violet", "coral", "blue", "mint"][index % 4]}`} style={{ width: `${item.progress}%` }} /></div><p>{item.chapter} · {item.completed_topics} of {item.total_topics} topics</p></div><button className="icon-button" onClick={() => update(item)} aria-label={`Update ${item.chapter}`}><Icon name="plus" size={16} /></button></article>)}</div></div>;
}

function PlannerWorkspace() {
  const [tasks, setTasks] = useState<PlanTask[]>([]); const [draft, setDraft] = useState("");
  useEffect(() => { apiFetch<PlanTask[]>("/api/v1/planner").then(setTasks).catch(() => setTasks([])); }, []);
  const toggle = async (task: PlanTask) => { const updated = await apiFetch<PlanTask>(`/api/v1/planner/${task.id}`, { method: "PATCH", body: JSON.stringify({ completed: !task.completed }) }); setTasks((current) => current.map((item) => item.id === task.id ? updated : item)); };
  const add = async (event: React.FormEvent) => { event.preventDefault(); if (!draft.trim()) return; const task = await apiFetch<PlanTask>("/api/v1/planner", { method: "POST", body: JSON.stringify({ title: draft.trim(), subject: "Custom task", due_date: new Date().toISOString().slice(0, 10), minutes: 30 }) }); setTasks((current) => [...current, task]); setDraft(""); };
  return <div className="planner-layout"><section className="dashboard-card planner-day"><div className="card-heading"><div><span className="section-kicker">Your study plan</span><h2>Plan for today</h2></div><span className="streak-pill"><Icon name="flame" size={14} /> {tasks.filter((task) => task.completed).length} complete</span></div>{tasks.length ? tasks.map((task) => <button className={`planner-task ${task.completed ? "planner-task-done" : ""}`} key={task.id} onClick={() => toggle(task)}><span className="task-check">{task.completed ? <Icon name="check" size={13} /> : null}</span><span className="task-copy"><strong>{task.title}</strong><small>{task.subject ?? "Study"} · {task.due_date}</small></span><span className="task-duration">{task.minutes} min</span><Icon name="arrow-right" size={15} /></button>) : <EmptyState icon="calendar-days" title="No tasks yet." body="Add your first study task below." />}{<form className="inline-add" onSubmit={add}><input value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Add a custom task" /><button className="icon-button" aria-label="Add task"><Icon name="plus" size={16} /></button></form>}</section><aside className="dashboard-card plan-sidebar"><span className="section-kicker">Plan health</span><strong>{tasks.length ? Math.round((tasks.filter((task) => task.completed).length / tasks.length) * 100) : 0}%</strong><p>of your persisted study tasks are complete.</p><Link href="/revision" className="outline-button">Build a revision plan <Icon name="arrow-up-right" size={14} /></Link></aside></div>;
}

function RevisionWorkspace() {
  const [items, setItems] = useState<RevisionItem[]>([]);
  useEffect(() => { apiFetch<RevisionItem[]>("/api/v1/revision").then(setItems).catch(() => setItems([])); }, []);
  const complete = async (item: RevisionItem) => { const updated = await apiFetch<RevisionItem>(`/api/v1/revision/${item.id}`, { method: "PATCH", body: JSON.stringify({ status: "completed" }) }); setItems((current) => current.filter((candidate) => candidate.id !== updated.id)); };
  return <div className="revision-layout"><div className="revision-timeline">{items.length ? items.map((item) => <article className={`revision-item revision-${item.status}`} key={item.id}><div className="revision-date"><strong>{new Date(item.due_at).getDate()}</strong><span>{new Date(item.due_at).toLocaleString("en-IN", { month: "short" }).toUpperCase()}</span></div><div className="revision-line" /><div className="revision-copy"><span className="section-kicker">{item.status}</span><h3>{item.title}</h3><p>{item.subject ?? "General"}</p></div><button className="button button-soft" onClick={() => complete(item)}>Complete</button></article>) : <EmptyState icon="rotate-ccw" title="Your revision queue is clear." body="Revision items generated from study activity will appear here." href="/planner" action="Open study planner" />}</div><aside className="dashboard-card revision-aside"><div className="section-kicker">Revision rhythm</div><h2>Return before recall fades.</h2><p>Completed revision items are removed from the active queue and remain in analytics.</p><Link href="/planner" className="button button-primary">Open study planner <Icon name="arrow-right" size={14} /></Link></aside></div>;
}

function VideosWorkspace() {
  const [watched, setWatched] = useState<string[]>([]); const videos = [{ title: "Consolidation in 90 minutes", faculty: "CA OS Faculty", duration: "1h 32m", type: "Revision lecture" }, { title: "Company Law · Directors", faculty: "Concept room", duration: "42m", type: "Concept video" }, { title: "Tax amendments for your attempt", faculty: "Exam update", duration: "28m", type: "Amendment" }];
  return <div className="video-grid">{videos.map((video) => <article className="video-card" key={video.title}><button className="video-thumbnail" onClick={() => setWatched((current) => current.includes(video.title) ? current : [...current, video.title])}><span className="play-button"><Icon name="play-square" size={20} /></span><span className="video-duration">{video.duration}</span></button><div className="video-card-copy"><span className="section-kicker">{video.type}</span><h3>{video.title}</h3><p>{video.faculty}</p><button className="text-button" onClick={() => setWatched((current) => current.includes(video.title) ? current : [...current, video.title])}>{watched.includes(video.title) ? "Watched" : "Watch now"} <Icon name="arrow-right" size={14} /></button></div></article>)}</div>;
}

function QueriesWorkspace() {
  const [body, setBody] = useState(""); const [queries, setQueries] = useState<QueryItem[]>([]); const [submitting, setSubmitting] = useState(false);
  useEffect(() => { apiFetch<QueryItem[]>("/api/v1/queries").then(setQueries).catch(() => setQueries([])); }, []);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!body.trim()) return; setSubmitting(true); try { const item = await apiFetch<QueryItem>("/api/v1/queries", { method: "POST", body: JSON.stringify({ subject: "General", title: body.trim().slice(0, 80), body: body.trim() }) }); setQueries((current) => [item, ...current]); setBody(""); } finally { setSubmitting(false); } };
  return <div className="query-layout"><section className="dashboard-card query-form-card"><div className="section-kicker">New query</div><h2>Ask with context.</h2><p>Your question is saved and can be answered by an assigned faculty member.</p><form onSubmit={submit}><input value={body} onChange={(event) => setBody(event.target.value)} placeholder="What are you unsure about?" required /><button className="button button-primary" disabled={submitting}>{submitting ? "Saving…" : "Submit query"} <Icon name="arrow-right" size={14} /></button></form></section><section className="dashboard-card query-list"><div className="card-heading"><div><span className="section-kicker">Your queue</span><h2>Queries and replies</h2></div></div>{queries.length ? queries.map((item) => <div className="query-row" key={item.id}><span className={`query-status query-status-${item.status.toLowerCase()}`} /> <div><strong>{item.title}</strong><small>{item.subject}{item.answer ? ` · ${item.answer}` : ""}</small></div><span>{item.status}</span><Icon name="arrow-right" size={15} /></div>) : <EmptyState icon="message-circle" title="No queries yet." body="Ask your first faculty question from the form." />}</section></div>;
}

function GenericWorkspace({ routeKey }: { routeKey: string }) {
  const copy = pageCopy[routeKey] ?? { eyebrow: "Workspace", title: "A focused space for your next step.", body: "This workspace is connected to the CA OS navigation and is ready for the next domain integration.", icon: "sparkles" };
  const [filter, setFilter] = useState(""); const [saved, setSaved] = useState<string[]>([]);
  const items = routeKey === "icai-updates" ? ["Exam form deadlines and official notices", "BOS learning resources", "Amendments for the current attempt"] : routeKey === "career" ? ["Audit and assurance roadmap", "Tax technology skill path", "Financial reporting opportunities"] : routeKey === "articleship" ? ["Audit articleship · Ahmedabad", "Industrial training · Financial reporting", "Risk advisory · Mumbai"] : ["Your saved study moments", "Recommended for your attempt", "Continue where you left off"];
  return <div className="generic-workspace"><div className="dashboard-card generic-intro"><div className="generic-intro-icon"><Icon name={copy.icon} size={23} /></div><div><span className="section-kicker">{routeKey === "ai" ? "AI-generated responses are always labelled" : "Connected workspace"}</span><h2>{routeKey === "ai" ? "Ask a focused question." : "A clear next step is better than a crowded page."}</h2><p>{routeKey === "ai" ? "Explain a concept, compare two ideas or turn a chapter into a revision checklist. Verify official rules against primary sources." : copy.body}</p></div></div><div className="feature-toolbar"><div className="feature-search"><Icon name="search" size={17} /><input value={filter} onChange={(event) => setFilter(event.target.value)} placeholder={`Search ${routeKey.replaceAll("-", " ")}`} /></div><button className="button button-primary" onClick={() => setSaved((current) => [...current, `New ${routeKey} item`])}><Icon name="plus" size={15} /> Add to workspace</button></div><div className="generic-list">{items.filter((item) => item.toLowerCase().includes(filter.toLowerCase())).map((item) => <article className="generic-row" key={item}><div className="generic-row-icon"><Icon name={copy.icon} size={17} /></div><div><strong>{item}</strong><small>{routeKey === "icai-updates" ? "Original source link available" : "Structured for your current attempt"}</small></div><button className={`icon-button ${saved.includes(item) ? "icon-button-active" : ""}`} onClick={() => setSaved((current) => current.includes(item) ? current.filter((entry) => entry !== item) : [...current, item])} aria-label="Save"><Icon name="bookmark" size={16} /></button><Icon name="arrow-right" size={15} /></article>)}</div>{saved.length ? <div className="inline-notice"><Icon name="check" size={15} /> {saved.length} item{saved.length > 1 ? "s" : ""} saved to your workspace.</div> : null}</div>;
}

function AdminMcqManager() {
  const [questions, setQuestions] = useState<McqItem[]>([]); const [status, setStatus] = useState<string | null>(null);
  const [form, setForm] = useState({ prompt: "", subject: "Advanced Accounting", chapter: "", explanation: "", difficulty: "medium", correct_option: "0", options: ["", "", "", ""] });
  useEffect(() => { apiFetch<McqItem[]>("/api/v1/mcqs").then(setQuestions).catch(() => setQuestions([])); }, []);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setStatus(null); try { const created = await apiFetch<McqItem>("/api/v1/mcqs", { method: "POST", body: JSON.stringify({ ...form, options: form.options, correct_option: Number(form.correct_option) }) }); setQuestions((current) => [created, ...current]); setStatus("MCQ published successfully."); setForm((current) => ({ ...current, prompt: "", explanation: "", options: ["", "", "", ""] })); } catch (error) { setStatus(error instanceof ApiError ? error.message : "Could not publish MCQ."); } };
  return <div className="admin-manager-layout"><section className="dashboard-card upload-card"><div className="section-kicker">Practice content</div><h2>Publish a real MCQ.</h2><form className="admin-upload-form" onSubmit={submit}><label>Question<input value={form.prompt} onChange={(event) => setForm({ ...form, prompt: event.target.value })} required /></label>{form.options.map((option, index) => <label key={index}>Option {String.fromCharCode(65 + index)}<input value={option} onChange={(event) => setForm({ ...form, options: form.options.map((item, itemIndex) => itemIndex === index ? event.target.value : item) })} required /></label>)}<div className="admin-two-col"><label>Subject<input value={form.subject} onChange={(event) => setForm({ ...form, subject: event.target.value })} required /></label><label>Correct option<select value={form.correct_option} onChange={(event) => setForm({ ...form, correct_option: event.target.value })}><option value="0">A</option><option value="1">B</option><option value="2">C</option><option value="3">D</option></select></label></div><label>Explanation<textarea value={form.explanation} onChange={(event) => setForm({ ...form, explanation: event.target.value })} required /></label>{status ? <div className="inline-notice"><Icon name="check" size={15} /> {status}</div> : null}<button className="button button-primary">Publish MCQ <Icon name="arrow-up-right" size={14} /></button></form></section><section className="dashboard-card generic-list"><div className="section-kicker">Published bank</div><h2>{questions.length} MCQ{questions.length === 1 ? "" : "s"}</h2>{questions.map((question) => <div className="generic-row" key={question.id}><div className="generic-row-icon"><Icon name="circle-help" size={17} /></div><div><strong>{question.prompt}</strong><small>{question.subject} · {question.chapter ?? "General"}</small></div></div>)}</section></div>;
}

function AdminTestManager() {
  const [questions, setQuestions] = useState<McqItem[]>([]); const [tests, setTests] = useState<TestItem[]>([]); const [status, setStatus] = useState<string | null>(null); const [title, setTitle] = useState(""); const [selected, setSelected] = useState<string[]>([]);
  useEffect(() => { apiFetch<McqItem[]>("/api/v1/mcqs").then(setQuestions).catch(() => setQuestions([])); apiFetch<TestItem[]>("/api/v1/tests").then(setTests).catch(() => setTests([])); }, []);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); try { const created = await apiFetch<TestItem>("/api/v1/tests", { method: "POST", body: JSON.stringify({ title, duration_minutes: 60, marks: selected.length, question_ids: selected }) }); setTests((current) => [created, ...current]); setTitle(""); setSelected([]); setStatus("Test published successfully."); } catch (error) { setStatus(error instanceof ApiError ? error.message : "Could not publish test."); } };
  return <div className="admin-manager-layout"><section className="dashboard-card upload-card"><div className="section-kicker">Assessment content</div><h2>Create a test.</h2><form className="admin-upload-form" onSubmit={submit}><label>Test title<input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="e.g. Consolidation chapter test" required /></label><div className="section-kicker">Select MCQs</div>{questions.length ? questions.map((question) => <label className="checkbox-row" key={question.id}><input type="checkbox" checked={selected.includes(question.id)} onChange={(event) => setSelected((current) => event.target.checked ? [...current, question.id] : current.filter((id) => id !== question.id))} />{question.prompt}</label>) : <p>Publish MCQs first.</p>}{status ? <div className="inline-notice"><Icon name="check" size={15} /> {status}</div> : null}<button className="button button-primary" disabled={!selected.length}>Publish test <Icon name="arrow-up-right" size={14} /></button></form></section><section className="dashboard-card generic-list"><div className="section-kicker">Test series</div><h2>{tests.length} test{tests.length === 1 ? "" : "s"}</h2>{tests.map((test) => <div className="generic-row" key={test.id}><div className="generic-row-icon"><Icon name="clipboard-check" size={17} /></div><div><strong>{test.title}</strong><small>{test.question_count} questions · {test.marks} marks</small></div></div>)}</section></div>;
}

function AdminWorkspace({ routeKey }: { routeKey: string }) {
  const [file, setFile] = useState<File | null>(null); const [form, setForm] = useState({ title: "", level: "CA Intermediate", subject: "Advanced Accounting", resource_type: "Study Material", attempt: "May 2027" }); const [status, setStatus] = useState<string | null>(null); const [uploading, setUploading] = useState(false);
  const isResourceManager = routeKey === "admin/resources" || routeKey === "admin";
  if (routeKey === "admin/mcqs") return <AdminMcqManager />;
  if (routeKey === "admin/tests") return <AdminTestManager />;
  async function upload(event: React.FormEvent) { event.preventDefault(); setStatus(null); setUploading(true); const body = new FormData(); Object.entries(form).forEach(([key, value]) => body.append(key, value)); if (file) body.append("file", file); try { const response = await fetch(`${API_BASE_URL}/api/v1/resources/upload`, { method: "POST", credentials: "include", body }); if (!response.ok) { const data = await response.json().catch(() => ({})); throw new Error(data.detail ?? "Upload failed"); } setStatus("Resource uploaded and available in the student library."); setForm((current) => ({ ...current, title: "" })); setFile(null); } catch (error) { setStatus(error instanceof Error ? error.message : "Upload failed. Check administrator access."); } finally { setUploading(false); } }
  if (!isResourceManager) return <AdminOverview />;
  return <div className="admin-manager-layout"><section className="dashboard-card upload-card"><div className="section-kicker">Content management</div><h2>Upload an authorised resource.</h2><p>Only upload material you are permitted to distribute. Files are validated and stored outside the public web root.</p><form className="admin-upload-form" onSubmit={upload}><label>Resource title<input value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder="e.g. RTP · Advanced Accounting · May 2027" required /></label><div className="admin-two-col"><label>Level<select value={form.level} onChange={(event) => setForm({ ...form, level: event.target.value })}><option>CA Foundation</option><option>CA Intermediate</option><option>CA Final</option></select></label><label>Subject<input value={form.subject} onChange={(event) => setForm({ ...form, subject: event.target.value })} required /></label></div><div className="admin-two-col"><label>Resource type<select value={form.resource_type} onChange={(event) => setForm({ ...form, resource_type: event.target.value })}><option>Study Material</option><option>RTP</option><option>MTP</option><option>PYQ</option><option>Suggested Answer</option><option>Notes</option><option>Amendment</option><option>Question Bank</option></select></label><label>Attempt<input value={form.attempt} onChange={(event) => setForm({ ...form, attempt: event.target.value })} /></label></div><label className="file-drop"><input type="file" accept=".pdf,.png,.jpg,.jpeg,.webp,.doc,.docx,.xls,.xlsx" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /> <Icon name="upload" size={20} /><strong>{file ? file.name : "Choose a file"}</strong><small>PDF, image, Word or Excel · max 15 MB</small></label>{status ? <div className="inline-notice"><Icon name="check" size={15} /> {status}</div> : null}<button className="button button-primary" type="submit" disabled={uploading}>{uploading ? "Uploading securely…" : "Upload resource"}<Icon name="arrow-up-right" size={14} /></button></form></section><aside className="admin-side-stack"><div className="dashboard-card admin-stat-card"><span className="section-kicker">Content health</span><strong>Ready to publish</strong><p>Every upload should carry level, subject, attempt and source metadata.</p></div><div className="dashboard-card admin-stat-card"><span className="section-kicker">Admin areas</span><Link href="/admin/students">Manage students <Icon name="arrow-right" size={14} /></Link><Link href="/admin/faculty">Manage faculty <Icon name="arrow-right" size={14} /></Link><Link href="/admin/audit-logs">Review audit logs <Icon name="arrow-right" size={14} /></Link></div></aside></div>;
}

function AdminOverview() { return <div className="admin-overview"><div className="admin-metric-grid">{[["Students", "0", "Live accounts"], ["Resources", "0", "Published items"], ["Pending queries", "0", "Need attention"], ["Evaluations", "0", "In the queue"]].map(([label, value, detail]) => <article className="metric-card metric-violet" key={label}><div className="metric-top"><span>{label}</span><Icon name="arrow-up-right" size={14} /></div><div className="metric-value-row"><strong>{value}</strong></div><div className="metric-bottom"><span>{detail}</span></div></article>)}</div><div className="admin-quick-grid"><Link href="/admin/resources" className="dashboard-card admin-quick-card"><Icon name="upload" size={20} /><div><span className="section-kicker">Content</span><h2>Upload resources</h2><p>Publish authorised study material for students.</p></div><Icon name="arrow-right" size={15} /></Link><Link href="/admin/mcqs" className="dashboard-card admin-quick-card"><Icon name="circle-help" size={20} /><div><span className="section-kicker">Practice</span><h2>Manage MCQs</h2><p>Create question banks for each subject.</p></div><Icon name="arrow-right" size={15} /></Link><Link href="/admin/announcements" className="dashboard-card admin-quick-card"><Icon name="bell" size={20} /><div><span className="section-kicker">Communication</span><h2>Announcements</h2><p>Keep students informed without clutter.</p></div><Icon name="arrow-right" size={15} /></Link></div></div>; }

function FacultyWorkspace() { return <div className="faculty-overview"><div className="admin-metric-grid">{[["Pending papers", "0", "Awaiting evaluation"], ["Open queries", "0", "Assigned to you"], ["Assigned students", "0", "Current scope"], ["Average response", "—", "This month"]].map(([label, value, detail]) => <article className="metric-card metric-blue" key={label}><div className="metric-top"><span>{label}</span><Icon name="arrow-up-right" size={14} /></div><div className="metric-value-row"><strong>{value}</strong></div><div className="metric-bottom"><span>{detail}</span></div></article>)}</div><div className="dashboard-card empty-faculty"><div className="empty-state-icon"><Icon name="briefcase-business" size={22} /></div><h2>Your faculty queue will appear here.</h2><p>Once an admin assigns subjects, batches or evaluations, this workspace will show only the students and papers within your scope.</p><Link href="/faculty/queries" className="button button-primary">Open query queue <Icon name="arrow-right" size={14} /></Link></div></div>; }

export function FeatureWorkspace({ segments }: { segments: string[] }) {
  const routeKey = segments.join("/") || "dashboard";
  if (routeKey.startsWith("admin")) return <><FeatureHeader copy={{ eyebrow: "Admin workspace", title: routeKey === "admin" ? "Run the platform with clarity." : "Manage the right thing next.", body: "Students, content, permissions and audit history in one controlled workspace.", icon: "shield-check" }} action={routeKey === "admin/resources" ? undefined : "Upload resource"} onAction={() => window.location.assign("/admin/resources")} /><AdminWorkspace routeKey={routeKey} /></>;
  if (routeKey.startsWith("faculty")) return <><FeatureHeader copy={{ eyebrow: "Faculty workspace", title: "Feedback that moves students forward.", body: "Evaluate, reply and support only the cohorts assigned to you.", icon: "briefcase-business" }} /><FacultyWorkspace /></>;
  if (routeKey === "resources") return <><FeatureHeader copy={{ eyebrow: "Study resources", title: "A calmer way to find the right material.", body: "Browse authorised study material by level, subject, attempt and chapter.", icon: "book-open" }} /><ResourceWorkspace /></>;
  const copy = pageCopy[segments[0]] ?? pageCopy[routeKey];
  if (segments[0] === "mcq") return <><FeatureHeader copy={copy} action="New practice" /><McqWorkspace /></>;
  if (segments[0] === "tests") return <><FeatureHeader copy={copy} action="Browse tests" /><TestsWorkspace /></>;
  if (segments[0] === "syllabus") return <><FeatureHeader copy={copy} /><SyllabusWorkspace /></>;
  if (segments[0] === "planner") return <><FeatureHeader copy={copy} action="Generate plan" /><PlannerWorkspace /></>;
  if (segments[0] === "revision") return <><FeatureHeader copy={copy} /><RevisionWorkspace /></>;
  if (segments[0] === "videos") return <><FeatureHeader copy={copy} /><VideosWorkspace /></>;
  if (segments[0] === "queries") return <><FeatureHeader copy={copy} action="Ask a doubt" /><QueriesWorkspace /></>;
  return <><FeatureHeader copy={copy ?? pageCopy.settings} /><GenericWorkspace routeKey={segments[0] ?? "settings"} /></>;
}
