"use client";

import type { Route } from "next";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Icon } from "@/components/icon";
import { apiFetch, ApiError, API_BASE_URL } from "@/lib/api-client";

type ResourceItem = {
  id: string;
  title: string;
  description?: string | null;
  level: string;
  subject: string;
  chapter?: string | null;
  resource_type: string;
  attempt?: string | null;
  year?: number | null;
  file_name?: string | null;
  file_size?: number | null;
  official_icai: boolean;
  bookmarked: boolean;
  completed: boolean;
  created_at: string;
};

const pageCopy: Record<string, { eyebrow: string; title: string; body: string; icon: string }> = {
  mcq: { eyebrow: "Practice with intent", title: "Build accuracy, one question at a time.", body: "Switch between chapter practice and your personal mistake book without losing your rhythm.", icon: "circle-help" },
  tests: { eyebrow: "Assessments", title: "Tests that tell you what to do next.", body: "Take timed tests, review your attempt and turn feedback into your next study block.", icon: "clipboard-check" },
  syllabus: { eyebrow: "Your progress", title: "See the syllabus move.", body: "Track every chapter from first read to final revision and keep the whole attempt visible.", icon: "chart-no-axes-combined" },
  planner: { eyebrow: "Study planner", title: "Make a plan you can actually keep.", body: "Shape your week around available hours, weak subjects and the exam date ahead.", icon: "calendar-days" },
  revision: { eyebrow: "Spaced revision", title: "Return at the right moment.", body: "Your revision queue brings important chapters back before they fade.", icon: "rotate-ccw" },
  videos: { eyebrow: "Video learning", title: "Learn at your pace.", body: "Keep lectures, marathons and quick concept refreshers in one focused place.", icon: "play-square" },
  "past-papers": { eyebrow: "Past paper analysis", title: "Study the pattern, not the prediction.", body: "Explore chapter frequency and marks distribution as preparation signals, never guarantees.", icon: "scan-search" },
  library: { eyebrow: "Your library", title: "Everything worth coming back to.", body: "Bookmarks, saved questions and completed resources stay close to your next session.", icon: "bookmark" },
  queries: { eyebrow: "Faculty support", title: "A clearer answer is one question away.", body: "Ask a structured doubt, add context and keep the reply with the chapter it belongs to.", icon: "message-circle" },
  ai: { eyebrow: "AI zone", title: "A study assistant with boundaries.", body: "Ask for explanations and revision help. Official rules and provisions always need a cited source.", icon: "sparkles" },
  articleship: { eyebrow: "Articleship", title: "Find the next place to grow.", body: "Explore opportunities, save promising roles and keep your applications organised.", icon: "briefcase-business" },
  career: { eyebrow: "Career", title: "Make your options concrete.", body: "Browse paths, skill roadmaps and practical next steps beyond the exam hall.", icon: "compass" },
  "icai-updates": { eyebrow: "Official updates", title: "Stay close to the source.", body: "Important exam, BOS and training updates with links back to the original official source.", icon: "landmark" },
  notifications: { eyebrow: "Notification centre", title: "Nothing important gets lost.", body: "Review test reminders, query responses and revision nudges in one calm feed.", icon: "bell" },
  profile: { eyebrow: "Your profile", title: "Keep your attempt details current.", body: "Your level, group and preferences help the platform recommend more useful work.", icon: "user-round" },
  settings: { eyebrow: "Workspace settings", title: "Make CA OS work your way.", body: "Manage theme, reminders, sessions and the details that shape your workspace.", icon: "settings" },
  timetable: { eyebrow: "Your calendar", title: "See the week at a glance.", body: "Classes, tests, live sessions and revisions in one timetable.", icon: "calendar-check" },
};

function FeatureHeader({ copy, action, onAction }: { copy: typeof pageCopy[string]; action?: string; onAction?: () => void }) {
  return <section className="feature-hero"><div><div className="eyebrow feature-eyebrow"><span className="feature-eyebrow-icon"><Icon name={copy.icon} size={14} /></span>{copy.eyebrow}</div><h1>{copy.title}</h1><p>{copy.body}</p></div>{action ? <button className="button button-primary button-with-icon" onClick={onAction}><Icon name="plus" size={16} /> {action}</button> : null}</section>;
}

function FilterChip({ active, children, onClick }: { active: boolean; children: React.ReactNode; onClick: () => void }) {
  return <button className={`filter-chip ${active ? "filter-chip-active" : ""}`} onClick={onClick}>{children}</button>;
}

function EmptyState({ icon, title, body, href, action }: { icon: string; title: string; body: string; href?: string; action?: string }) {
  return <div className="empty-state"><div className="empty-state-icon"><Icon name={icon} size={22} /></div><h3>{title}</h3><p>{body}</p>{href && action ? <Link href={href as Route} className="button button-primary">{action}<Icon name="arrow-right" size={14} /></Link> : null}</div>;
}

function ResourceWorkspace() {
  const [resources, setResources] = useState<ResourceItem[]>([]);
  const [query, setQuery] = useState("");
  const [type, setType] = useState("All");
  const [loading, setLoading] = useState(true);
  const [notice, setNotice] = useState<string | null>(null);

  useEffect(() => {
    apiFetch<ResourceItem[]>("/api/v1/resources").then(setResources).catch(() => setResources([])).finally(() => setLoading(false));
  }, []);

  const types = ["All", ...Array.from(new Set(resources.map((resource) => resource.resource_type)))];
  const filtered = resources.filter((resource) => `${resource.title} ${resource.subject} ${resource.chapter ?? ""}`.toLowerCase().includes(query.toLowerCase()) && (type === "All" || resource.resource_type === type));
  const toggleBookmark = async (resource: ResourceItem) => {
    try { await apiFetch(`/api/v1/resources/${resource.id}/bookmark`, { method: "POST" }); setResources((current) => current.map((item) => item.id === resource.id ? { ...item, bookmarked: !item.bookmarked } : item)); setNotice(resource.bookmarked ? "Removed from your library" : "Saved to your library"); } catch (error) { setNotice(error instanceof ApiError ? error.message : "Could not update your library"); }
  };
  const complete = async (resource: ResourceItem) => {
    try { await apiFetch(`/api/v1/resources/${resource.id}/progress`, { method: "PATCH", body: JSON.stringify({ completed: !resource.completed }) }); setResources((current) => current.map((item) => item.id === resource.id ? { ...item, completed: !item.completed } : item)); } catch { setNotice("Could not update progress"); }
  };

  return <><div className="feature-toolbar"><div className="feature-search"><Icon name="search" size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search title, subject or chapter" /></div><Link href="/admin/resources" className="button button-primary button-with-icon"><Icon name="plus" size={15} /> Upload resource</Link></div><div className="filter-row">{types.map((item) => <FilterChip active={type === item} key={item} onClick={() => setType(item)}>{item}</FilterChip>)}</div>{notice ? <div className="inline-notice"><Icon name="check" size={15} /> {notice}</div> : null}{loading ? <div className="resource-grid">{[1, 2, 3].map((item) => <div className="skeleton-card" key={item} />)}</div> : filtered.length ? <div className="resource-grid">{filtered.map((resource) => <article className="resource-card" key={resource.id}><div className="resource-card-top"><div className="resource-file-icon"><Icon name="file-text" size={20} /></div><button className={`icon-button ${resource.bookmarked ? "icon-button-active" : ""}`} onClick={() => toggleBookmark(resource)} aria-label={resource.bookmarked ? "Remove bookmark" : "Bookmark resource"}><Icon name="bookmark" size={16} /></button></div><div className="resource-card-body"><div className="resource-type-line"><span>{resource.resource_type}</span>{resource.official_icai ? <span className="official-badge">Official source</span> : null}</div><h3>{resource.title}</h3><p>{resource.subject}{resource.chapter ? ` · ${resource.chapter}` : ""}</p></div><div className="resource-card-footer"><span>{resource.file_name ?? resource.attempt ?? "Resource"}</span><div className="resource-card-actions">{resource.file_name ? <button onClick={() => window.open(`${API_BASE_URL}/api/v1/resources/${resource.id}/download`, "_blank", "noopener,noreferrer")}><Icon name="download" size={13} /> Download</button> : null}<button className={resource.completed ? "completed-action" : ""} onClick={() => complete(resource)}>{resource.completed ? <><Icon name="check" size={13} /> Completed</> : "Mark complete"}</button></div></div></article>)}</div> : <EmptyState icon="book-open" title="Your resource shelf is ready." body="Once an admin uploads authorised study material, it will appear here with filters, bookmarks and progress tracking." href="/admin/resources" action="Open content manager" />}</>;
}

function McqWorkspace() {
  const questions = [
    { chapter: "Consolidation", text: "Which statement best describes the purpose of a consolidated financial statement?", options: ["To present the parent and its subsidiaries as one economic entity", "To replace every individual ledger", "To calculate only the parent company’s tax", "To report cash transactions only"], answer: 0, explanation: "Consolidated statements present the parent and its subsidiaries as a single economic entity." },
    { chapter: "Company Law", text: "A good revision question should help you identify the concept behind the answer. Which habit helps most?", options: ["Review only the option letter", "Read the explanation and note the rule", "Skip incorrect questions permanently", "Memorise the question number"], answer: 1, explanation: "The explanation and underlying rule are more valuable than memorising an option letter." },
    { chapter: "Taxation", text: "What is the most useful first action after getting an MCQ wrong?", options: ["Delete it", "Guess faster next time", "Record the concept and revisit it", "Avoid that chapter"], answer: 2, explanation: "The wrong-answer book turns mistakes into a targeted revision queue." },
  ];
  const [index, setIndex] = useState(0); const [selected, setSelected] = useState<number | null>(null); const [submitted, setSubmitted] = useState(false); const question = questions[index];
  const submit = () => { if (selected !== null) setSubmitted(true); }; const next = () => { setIndex((current) => (current + 1) % questions.length); setSelected(null); setSubmitted(false); };
  return <div className="practice-layout"><section className="practice-card"><div className="practice-meta"><span>Question {index + 1} of {questions.length}</span><span>{question.chapter}</span></div><div className="practice-progress"><span style={{ width: `${((index + 1) / questions.length) * 100}%` }} /></div><h2>{question.text}</h2><div className="option-list">{question.options.map((option, optionIndex) => <button key={option} className={`option-row ${selected === optionIndex ? "option-selected" : ""} ${submitted && optionIndex === question.answer ? "option-correct" : ""} ${submitted && selected === optionIndex && selected !== question.answer ? "option-wrong" : ""}`} onClick={() => !submitted && setSelected(optionIndex)}><span>{String.fromCharCode(65 + optionIndex)}</span>{option}{submitted && optionIndex === question.answer ? <Icon name="check" size={16} /> : null}</button>)}</div>{submitted ? <div className={`answer-explanation ${selected === question.answer ? "answer-success" : "answer-error"}`}><strong>{selected === question.answer ? "Correct. Keep that concept." : "Review this one before moving on."}</strong><p>{question.explanation}</p></div> : null}<div className="practice-actions">{submitted ? <button className="button button-primary" onClick={next}>Next question <Icon name="arrow-right" size={15} /></button> : <button className="button button-primary" onClick={submit} disabled={selected === null}>Submit answer</button>}<Link href="/mcq/mistakes" className="text-button">My mistakes <Icon name="arrow-right" size={14} /></Link></div></section><aside className="practice-side"><div className="mini-score"><span className="section-kicker">This session</span><strong>0%</strong><p>Answer a question to start your accuracy trail.</p></div><div className="side-list"><span className="section-kicker">Practice modes</span><Link href="/mcq">Chapter wise <Icon name="arrow-right" size={14} /></Link><Link href="/mcq">Weak questions <Icon name="arrow-right" size={14} /></Link><Link href="/mcq">Bookmarked <Icon name="arrow-right" size={14} /></Link><Link href="/mcq/mistakes">Wrong answers <Icon name="arrow-right" size={14} /></Link></div></aside></div>;
}

function TestsWorkspace() {
  const tests = [{ name: "Advanced Accounting · Consolidation", type: "Chapter test", duration: "60 min", marks: "45 marks", status: "Open" }, { name: "Corporate Law · Selected chapters", type: "Revision test", duration: "45 min", marks: "30 marks", status: "Upcoming" }, { name: "Group 1 full syllabus mock", type: "Mock test", duration: "3 hours", marks: "100 marks", status: "Locked" }];
  const [started, setStarted] = useState<string | null>(null);
  return <div className="test-list">{tests.map((test) => <article className="test-card" key={test.name}><div className="test-card-icon"><Icon name="clipboard-check" size={20} /></div><div className="test-card-copy"><span className="section-kicker">{test.type}</span><h3>{test.name}</h3><p><span><Icon name="clock-3" size={13} /> {test.duration}</span><span><Icon name="file-text" size={13} /> {test.marks}</span></p></div><div className="test-card-action">{started === test.name ? <span className="inline-status"><i /> Ready to begin</span> : <button className="button button-soft" onClick={() => setStarted(test.name)} disabled={test.status === "Locked"}>{test.status === "Locked" ? "Locked" : test.status === "Open" ? "Start test" : "Set reminder"}<Icon name="arrow-right" size={14} /></button>}</div></article>)}</div>;
}

function SyllabusWorkspace() {
  const [subjects, setSubjects] = useState([{ name: "Advanced Accounting", percent: 72, chapters: "8 of 11 chapters", tone: "violet" }, { name: "Corporate & Other Laws", percent: 55, chapters: "6 of 10 chapters", tone: "coral" }, { name: "Taxation", percent: 43, chapters: "4 of 9 chapters", tone: "blue" }, { name: "Cost & Management Accounting", percent: 68, chapters: "6 of 8 chapters", tone: "mint" }]);
  const update = (name: string) => setSubjects((items) => items.map((item) => item.name === name ? { ...item, percent: Math.min(100, item.percent + 5) } : item));
  return <div className="syllabus-layout"><section className="dashboard-card syllabus-overview"><div className="radial-progress"><span><strong>64%</strong><small>overall</small></span></div><div><span className="section-kicker">Current attempt</span><h2>18 of 28 chapters in motion.</h2><p>Complete a chapter or move a concept into revision to keep this score current.</p></div></section><div className="subject-progress-grid">{subjects.map((subject) => <article className="subject-progress-card" key={subject.name}><div className={`subject-badge subject-${subject.tone}`}>{subject.name.split(" ").map((word) => word[0]).join("").slice(0, 3)}</div><div className="subject-progress-copy"><div><h3>{subject.name}</h3><strong>{subject.percent}%</strong></div><div className="progress-track"><span className={`progress-fill fill-${subject.tone}`} style={{ width: `${subject.percent}%` }} /></div><p>{subject.chapters}</p></div><button className="icon-button" onClick={() => update(subject.name)} aria-label={`Update ${subject.name}`}><Icon name="plus" size={16} /></button></article>)}</div></div>;
}

function PlannerWorkspace() {
  const [tasks, setTasks] = useState([{ title: "Consolidated financial statements", subject: "Advanced Accounting", time: "90 min", done: false }, { title: "Company Law MCQ sprint", subject: "Law", time: "20 questions", done: false }, { title: "House property revision", subject: "Taxation", time: "30 min", done: true }]);
  const [draft, setDraft] = useState("");
  return <div className="planner-layout"><section className="dashboard-card planner-day"><div className="card-heading"><div><span className="section-kicker">Monday · 23 September</span><h2>Your plan for today</h2></div><span className="streak-pill"><Icon name="flame" size={14} /> 12 days</span></div>{tasks.map((task, index) => <button className={`planner-task ${task.done ? "planner-task-done" : ""}`} key={task.title} onClick={() => setTasks((items) => items.map((item, taskIndex) => taskIndex === index ? { ...item, done: !item.done } : item))}><span className="task-check">{task.done ? <Icon name="check" size={13} /> : null}</span><span className="task-copy"><strong>{task.title}</strong><small>{task.subject}</small></span><span className="task-duration">{task.time}</span><Icon name="arrow-right" size={15} /></button>)}<form className="inline-add" onSubmit={(event) => { event.preventDefault(); if (draft.trim()) { setTasks((items) => [...items, { title: draft.trim(), subject: "Custom task", time: "30 min", done: false }]); setDraft(""); } }}><input value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Add a custom task" /><button className="icon-button" aria-label="Add task"><Icon name="plus" size={16} /></button></form></section><aside className="dashboard-card plan-sidebar"><span className="section-kicker">Plan health</span><strong>78%</strong><p>of your planned study time is complete this week.</p><div className="progress-track"><span className="progress-fill fill-mint" style={{ width: "78%" }} /></div><Link href="/revision" className="outline-button">Build a revision plan <Icon name="arrow-up-right" size={14} /></Link></aside></div>;
}

function RevisionWorkspace() {
  const [items, setItems] = useState([{ title: "Partnership accounts", subject: "Advanced Accounting", due: "Due today", state: "Due" }, { title: "Directors and meetings", subject: "Corporate Law", due: "Tomorrow", state: "Upcoming" }, { title: "Residential status", subject: "Taxation", due: "30 Sep", state: "Upcoming" }]);
  return <div className="revision-layout"><div className="revision-timeline">{items.map((item, index) => <article className={`revision-item revision-${item.state.toLowerCase()}`} key={item.title}><div className="revision-date"><strong>{index === 0 ? "23" : index === 1 ? "24" : "30"}</strong><span>SEP</span></div><div className="revision-line" /><div className="revision-copy"><span className="section-kicker">{item.due}</span><h3>{item.title}</h3><p>{item.subject} · Revision {index + 1}</p></div><button className="button button-soft" onClick={() => setItems((current) => current.filter((candidate) => candidate.title !== item.title))}>{item.state === "Due" ? "Complete" : "Snooze"}</button></article>)}</div><aside className="dashboard-card revision-aside"><div className="section-kicker">Revision rhythm</div><h2>Return before recall fades.</h2><p>Your schedule spaces the next review based on completion and confidence.</p><Link href="/planner" className="button button-primary">Open study planner <Icon name="arrow-right" size={14} /></Link></aside></div>;
}

function VideosWorkspace() {
  const [watched, setWatched] = useState<string[]>([]); const videos = [{ title: "Consolidation in 90 minutes", faculty: "CA OS Faculty", duration: "1h 32m", type: "Revision lecture" }, { title: "Company Law · Directors", faculty: "Concept room", duration: "42m", type: "Concept video" }, { title: "Tax amendments for your attempt", faculty: "Exam update", duration: "28m", type: "Amendment" }];
  return <div className="video-grid">{videos.map((video) => <article className="video-card" key={video.title}><button className="video-thumbnail" onClick={() => setWatched((current) => current.includes(video.title) ? current : [...current, video.title])}><span className="play-button"><Icon name="play-square" size={20} /></span><span className="video-duration">{video.duration}</span></button><div className="video-card-copy"><span className="section-kicker">{video.type}</span><h3>{video.title}</h3><p>{video.faculty}</p><button className="text-button" onClick={() => setWatched((current) => current.includes(video.title) ? current : [...current, video.title])}>{watched.includes(video.title) ? "Watched" : "Watch now"} <Icon name="arrow-right" size={14} /></button></div></article>)}</div>;
}

function QueriesWorkspace() {
  const [query, setQuery] = useState(""); const [queries, setQueries] = useState([{ title: "Treatment of goodwill on admission", subject: "Advanced Accounting", status: "Answered" }, { title: "Clarification on section 135", subject: "Corporate Law", status: "Open" }]);
  return <div className="query-layout"><section className="dashboard-card query-form-card"><div className="section-kicker">New query</div><h2>Ask with context.</h2><p>Choose the subject and add the exact point where you got stuck.</p><form onSubmit={(event) => { event.preventDefault(); if (query.trim()) { setQueries((current) => [{ title: query.trim(), subject: "Advanced Accounting", status: "Open" }, ...current]); setQuery(""); } }}><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="What are you unsure about?" required /><button className="button button-primary">Submit query <Icon name="arrow-right" size={14} /></button></form></section><section className="dashboard-card query-list"><div className="card-heading"><div><span className="section-kicker">Your queue</span><h2>Queries and replies</h2></div></div>{queries.map((item) => <div className="query-row" key={item.title}><span className={`query-status query-status-${item.status.toLowerCase()}`} /> <div><strong>{item.title}</strong><small>{item.subject}</small></div><span>{item.status}</span><Icon name="arrow-right" size={15} /></div>)}</section></div>;
}

function GenericWorkspace({ routeKey }: { routeKey: string }) {
  const copy = pageCopy[routeKey] ?? { eyebrow: "Workspace", title: "A focused space for your next step.", body: "This workspace is connected to the CA OS navigation and is ready for the next domain integration.", icon: "sparkles" };
  const [filter, setFilter] = useState(""); const [saved, setSaved] = useState<string[]>([]);
  const items = routeKey === "icai-updates" ? ["Exam form deadlines and official notices", "BOS learning resources", "Amendments for the current attempt"] : routeKey === "career" ? ["Audit and assurance roadmap", "Tax technology skill path", "Financial reporting opportunities"] : routeKey === "articleship" ? ["Audit articleship · Ahmedabad", "Industrial training · Financial reporting", "Risk advisory · Mumbai"] : ["Your saved study moments", "Recommended for your attempt", "Continue where you left off"];
  return <div className="generic-workspace"><div className="dashboard-card generic-intro"><div className="generic-intro-icon"><Icon name={copy.icon} size={23} /></div><div><span className="section-kicker">{routeKey === "ai" ? "AI-generated responses are always labelled" : "Connected workspace"}</span><h2>{routeKey === "ai" ? "Ask a focused question." : "A clear next step is better than a crowded page."}</h2><p>{routeKey === "ai" ? "Explain a concept, compare two ideas or turn a chapter into a revision checklist. Verify official rules against primary sources." : copy.body}</p></div></div><div className="feature-toolbar"><div className="feature-search"><Icon name="search" size={17} /><input value={filter} onChange={(event) => setFilter(event.target.value)} placeholder={`Search ${routeKey.replaceAll("-", " ")}`} /></div><button className="button button-primary" onClick={() => setSaved((current) => [...current, `New ${routeKey} item`])}><Icon name="plus" size={15} /> Add to workspace</button></div><div className="generic-list">{items.filter((item) => item.toLowerCase().includes(filter.toLowerCase())).map((item) => <article className="generic-row" key={item}><div className="generic-row-icon"><Icon name={copy.icon} size={17} /></div><div><strong>{item}</strong><small>{routeKey === "icai-updates" ? "Original source link available" : "Structured for your current attempt"}</small></div><button className={`icon-button ${saved.includes(item) ? "icon-button-active" : ""}`} onClick={() => setSaved((current) => current.includes(item) ? current.filter((entry) => entry !== item) : [...current, item])} aria-label="Save"><Icon name="bookmark" size={16} /></button><Icon name="arrow-right" size={15} /></article>)}</div>{saved.length ? <div className="inline-notice"><Icon name="check" size={15} /> {saved.length} item{saved.length > 1 ? "s" : ""} saved to your workspace.</div> : null}</div>;
}

function AdminWorkspace({ routeKey }: { routeKey: string }) {
  const [file, setFile] = useState<File | null>(null); const [form, setForm] = useState({ title: "", level: "CA Intermediate", subject: "Advanced Accounting", resource_type: "Study Material", attempt: "May 2027" }); const [status, setStatus] = useState<string | null>(null); const [uploading, setUploading] = useState(false);
  const isResourceManager = routeKey === "admin/resources" || routeKey === "admin";
  async function upload(event: React.FormEvent) { event.preventDefault(); setStatus(null); setUploading(true); const body = new FormData(); Object.entries(form).forEach(([key, value]) => body.append(key, value)); if (file) body.append("file", file); try { const response = await fetch(`${API_BASE_URL}/api/v1/resources/upload`, { method: "POST", credentials: "include", body }); if (!response.ok) { const data = await response.json().catch(() => ({})); throw new Error(data.detail ?? "Upload failed"); } setStatus("Resource uploaded and available in the student library."); setForm((current) => ({ ...current, title: "" })); setFile(null); } catch (error) { setStatus(error instanceof Error ? error.message : "Upload failed. Check administrator access."); } finally { setUploading(false); } }
  if (!isResourceManager) return <AdminOverview />;
  return <div className="admin-manager-layout"><section className="dashboard-card upload-card"><div className="section-kicker">Content management</div><h2>Upload an authorised resource.</h2><p>Only upload material you are permitted to distribute. Files are validated and stored outside the public web root.</p><form className="admin-upload-form" onSubmit={upload}><label>Resource title<input value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder="e.g. RTP · Advanced Accounting · May 2027" required /></label><div className="admin-two-col"><label>Level<select value={form.level} onChange={(event) => setForm({ ...form, level: event.target.value })}><option>CA Foundation</option><option>CA Intermediate</option><option>CA Final</option></select></label><label>Subject<input value={form.subject} onChange={(event) => setForm({ ...form, subject: event.target.value })} required /></label></div><div className="admin-two-col"><label>Resource type<select value={form.resource_type} onChange={(event) => setForm({ ...form, resource_type: event.target.value })}><option>Study Material</option><option>RTP</option><option>MTP</option><option>PYQ</option><option>Suggested Answer</option><option>Notes</option><option>Amendment</option><option>Question Bank</option></select></label><label>Attempt<input value={form.attempt} onChange={(event) => setForm({ ...form, attempt: event.target.value })} /></label></div><label className="file-drop"><input type="file" accept=".pdf,.png,.jpg,.jpeg,.webp,.doc,.docx,.xls,.xlsx" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /> <Icon name="upload" size={20} /><strong>{file ? file.name : "Choose a file"}</strong><small>PDF, image, Word or Excel · max 15 MB</small></label>{status ? <div className="inline-notice"><Icon name="check" size={15} /> {status}</div> : null}<button className="button button-primary" type="submit" disabled={uploading}>{uploading ? "Uploading securely…" : "Upload resource"}<Icon name="arrow-up-right" size={14} /></button></form></section><aside className="admin-side-stack"><div className="dashboard-card admin-stat-card"><span className="section-kicker">Content health</span><strong>Ready to publish</strong><p>Every upload should carry level, subject, attempt and source metadata.</p></div><div className="dashboard-card admin-stat-card"><span className="section-kicker">Admin areas</span><Link href="/admin/students">Manage students <Icon name="arrow-right" size={14} /></Link><Link href="/admin/faculty">Manage faculty <Icon name="arrow-right" size={14} /></Link><Link href="/admin/audit-logs">Review audit logs <Icon name="arrow-right" size={14} /></Link></div></aside></div>;
}

function AdminOverview() { return <div className="admin-overview"><div className="admin-metric-grid">{[["Students", "0", "Live accounts"], ["Resources", "0", "Published items"], ["Pending queries", "0", "Need attention"], ["Evaluations", "0", "In the queue"]].map(([label, value, detail]) => <article className="metric-card metric-violet" key={label}><div className="metric-top"><span>{label}</span><Icon name="arrow-up-right" size={14} /></div><div className="metric-value-row"><strong>{value}</strong></div><div className="metric-bottom"><span>{detail}</span></div></article>)}</div><div className="admin-quick-grid"><Link href="/admin/resources" className="dashboard-card admin-quick-card"><Icon name="upload" size={20} /><div><span className="section-kicker">Content</span><h2>Upload resources</h2><p>Publish authorised study material for students.</p></div><Icon name="arrow-right" size={15} /></Link><Link href="/admin/mcqs" className="dashboard-card admin-quick-card"><Icon name="circle-help" size={20} /><div><span className="section-kicker">Practice</span><h2>Manage MCQs</h2><p>Create question banks for each subject.</p></div><Icon name="arrow-right" size={15} /></Link><Link href="/admin/announcements" className="dashboard-card admin-quick-card"><Icon name="bell" size={20} /><div><span className="section-kicker">Communication</span><h2>Announcements</h2><p>Keep students informed without clutter.</p></div><Icon name="arrow-right" size={15} /></Link></div></div>; }

function FacultyWorkspace() { return <div className="faculty-overview"><div className="admin-metric-grid">{[["Pending papers", "0", "Awaiting evaluation"], ["Open queries", "0", "Assigned to you"], ["Assigned students", "0", "Current scope"], ["Average response", "—", "This month"]].map(([label, value, detail]) => <article className="metric-card metric-blue" key={label}><div className="metric-top"><span>{label}</span><Icon name="arrow-up-right" size={14} /></div><div className="metric-value-row"><strong>{value}</strong></div><div className="metric-bottom"><span>{detail}</span></div></article>)}</div><div className="dashboard-card empty-faculty"><div className="empty-state-icon"><Icon name="briefcase-business" size={22} /></div><h2>Your faculty queue will appear here.</h2><p>Once an admin assigns subjects, batches or evaluations, this workspace will show only the students and papers within your scope.</p><Link href="/faculty/queries" className="button button-primary">Open query queue <Icon name="arrow-right" size={14} /></Link></div></div>; }

export function FeatureWorkspace({ segments }: { segments: string[] }) {
  const routeKey = segments.join("/") || "dashboard";
  if (routeKey.startsWith("admin")) return <><FeatureHeader copy={{ eyebrow: "Admin workspace", title: routeKey === "admin" ? "Run the platform with clarity." : "Manage the right thing next.", body: "Students, content, permissions and audit history in one controlled workspace.", icon: "shield-check" }} action={routeKey === "admin/resources" ? undefined : "Upload resource"} onAction={() => window.location.assign("/admin/resources")} /><AdminWorkspace routeKey={routeKey} /></>;
  if (routeKey.startsWith("faculty")) return <><FeatureHeader copy={{ eyebrow: "Faculty workspace", title: "Feedback that moves students forward.", body: "Evaluate, reply and support only the cohorts assigned to you.", icon: "briefcase-business" }} /><FacultyWorkspace /></>;
  if (routeKey === "resources") return <><FeatureHeader copy={{ eyebrow: "Study resources", title: "A calmer way to find the right material.", body: "Browse authorised study material by level, subject, attempt and chapter.", icon: "book-open" }} /><ResourceWorkspace /></>;
  const copy = pageCopy[segments[0]] ?? pageCopy[routeKey];
  if (segments[0] === "mcq") return <><FeatureHeader copy={copy} action="New practice" /><McqWorkspace /></>;
  if (segments[0] === "tests") return <><FeatureHeader copy={copy} action="Browse tests" /><TestsWorkspace /></>;
  if (segments[0] === "syllabus") return <><FeatureHeader copy={copy} /><SyllabusWorkspace /></>;
  if (segments[0] === "planner") return <><FeatureHeader copy={copy} action="Generate plan" /><PlannerWorkspace /></>;
  if (segments[0] === "revision") return <><FeatureHeader copy={copy} /><RevisionWorkspace /></>;
  if (segments[0] === "videos") return <><FeatureHeader copy={copy} /><VideosWorkspace /></>;
  if (segments[0] === "queries") return <><FeatureHeader copy={copy} action="Ask a doubt" /><QueriesWorkspace /></>;
  return <><FeatureHeader copy={copy ?? pageCopy.settings} /><GenericWorkspace routeKey={segments[0] ?? "settings"} /></>;
}
