import type { LucideIcon } from "lucide-react";
import {
  ArrowRight,
  ArrowUpRight,
  Bell,
  BookOpen,
  Bookmark,
  BriefcaseBusiness,
  CalendarCheck2,
  CalendarDays,
  ChartNoAxesCombined,
  Check,
  ChevronDown,
  Circle,
  CircleHelp,
  ClipboardCheck,
  Clock3,
  Download,
  Command,
  Compass,
  FileText,
  Flame,
  LayoutDashboard,
  Landmark,
  Lock,
  LogOut,
  Menu,
  MessageCircle,
  MoreHorizontal,
  Moon,
  PlaySquare,
  Plus,
  RotateCcw,
  RefreshCw,
  ScanSearch,
  Search,
  Settings,
  ShieldCheck,
  Sparkles,
  Sun,
  Upload,
  UserRound,
  X,
} from "lucide-react";

const icons: Record<string, LucideIcon> = {
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  bell: Bell,
  "book-open": BookOpen,
  bookmark: Bookmark,
  "briefcase-business": BriefcaseBusiness,
  "calendar-check": CalendarCheck2,
  "calendar-days": CalendarDays,
  "chart-no-axes-combined": ChartNoAxesCombined,
  check: Check,
  "chevron-down": ChevronDown,
  circle: Circle,
  "circle-help": CircleHelp,
  "clipboard-check": ClipboardCheck,
  download: Download,
  "clock-3": Clock3,
  command: Command,
  compass: Compass,
  "file-text": FileText,
  flame: Flame,
  "layout-dashboard": LayoutDashboard,
  landmark: Landmark,
  lock: Lock,
  "log-out": LogOut,
  menu: Menu,
  "message-circle": MessageCircle,
  "more-horizontal": MoreHorizontal,
  moon: Moon,
  "play-square": PlaySquare,
  plus: Plus,
  "rotate-ccw": RotateCcw,
  "refresh-cw": RefreshCw,
  "scan-search": ScanSearch,
  search: Search,
  settings: Settings,
  "shield-check": ShieldCheck,
  sparkles: Sparkles,
  sun: Sun,
  upload: Upload,
  "user-round": UserRound,
  x: X,
};

export function Icon({ name, size = 18, strokeWidth = 1.8 }: { name: string; size?: number; strokeWidth?: number }) {
  const Component = icons[name] ?? Circle;
  return <Component size={size} strokeWidth={strokeWidth} aria-hidden="true" />;
}
